return {
	{'.placeholder-opacity-0', '__tw_placeholder_opacity__0;', base=true},
	{'.placeholder-opacity-5', '__tw_placeholder_opacity__0.05;', base=true},
	{'.placeholder-opacity-10', '__tw_placeholder_opacity__0.1;', base=true},
	{'.placeholder-opacity-20', '__tw_placeholder_opacity__0.2;', base=true},
	{'.placeholder-opacity-25', '__tw_placeholder_opacity__0.25;', base=true},
	{'.placeholder-opacity-30', '__tw_placeholder_opacity__0.3;', base=true},
	{'.placeholder-opacity-40', '__tw_placeholder_opacity__0.4;', base=true},
	{'.placeholder-opacity-50', '__tw_placeholder_opacity__0.5;', base=true},
	{'.placeholder-opacity-60', '__tw_placeholder_opacity__0.6;', base=true},
	{'.placeholder-opacity-70', '__tw_placeholder_opacity__0.7;', base=true},
	{'.placeholder-opacity-75', '__tw_placeholder_opacity__0.75;', base=true},
	{'.placeholder-opacity-80', '__tw_placeholder_opacity__0.8;', base=true},
	{'.placeholder-opacity-90', '__tw_placeholder_opacity__0.9;', base=true},
	{'.placeholder-opacity-95', '__tw_placeholder_opacity__0.95;', base=true},
	{'.placeholder-opacity-100', '__tw_placeholder_opacity__1;', base=true},
}