return {
	{'.bg-blend-normal', 'background-blend-mode: normal;', base=true},
	{'.bg-blend-multiply', 'background-blend-mode: multiply;', base=true},
	{'.bg-blend-screen', 'background-blend-mode: screen;', base=true},
	{'.bg-blend-overlay', 'background-blend-mode: overlay;', base=true},
	{'.bg-blend-darken', 'background-blend-mode: darken;', base=true},
	{'.bg-blend-lighten', 'background-blend-mode: lighten;', base=true},
	{'.bg-blend-color-dodge', 'background-blend-mode: color-dodge;', base=true},
	{'.bg-blend-color-burn', 'background-blend-mode: color-burn;', base=true},
	{'.bg-blend-hard-light', 'background-blend-mode: hard-light;', base=true},
	{'.bg-blend-soft-light', 'background-blend-mode: soft-light;', base=true},
	{'.bg-blend-difference', 'background-blend-mode: difference;', base=true},
	{'.bg-blend-exclusion', 'background-blend-mode: exclusion;', base=true},
	{'.bg-blend-hue', 'background-blend-mode: hue;', base=true},
	{'.bg-blend-saturation', 'background-blend-mode: saturation;', base=true},
	{'.bg-blend-color', 'background-blend-mode: color;', base=true},
	{'.bg-blend-luminosity', 'background-blend-mode: luminosity;', base=true},
}