return {
	{'.backdrop-opacity-0', '__tw_backdrop_opacity__opacity(0);', base=true},
	{'.backdrop-opacity-5', '__tw_backdrop_opacity__opacity(0.05);', base=true},
	{'.backdrop-opacity-10', '__tw_backdrop_opacity__opacity(0.1);', base=true},
	{'.backdrop-opacity-20', '__tw_backdrop_opacity__opacity(0.2);', base=true},
	{'.backdrop-opacity-25', '__tw_backdrop_opacity__opacity(0.25);', base=true},
	{'.backdrop-opacity-30', '__tw_backdrop_opacity__opacity(0.3);', base=true},
	{'.backdrop-opacity-40', '__tw_backdrop_opacity__opacity(0.4);', base=true},
	{'.backdrop-opacity-50', '__tw_backdrop_opacity__opacity(0.5);', base=true},
	{'.backdrop-opacity-60', '__tw_backdrop_opacity__opacity(0.6);', base=true},
	{'.backdrop-opacity-70', '__tw_backdrop_opacity__opacity(0.7);', base=true},
	{'.backdrop-opacity-75', '__tw_backdrop_opacity__opacity(0.75);', base=true},
	{'.backdrop-opacity-80', '__tw_backdrop_opacity__opacity(0.8);', base=true},
	{'.backdrop-opacity-90', '__tw_backdrop_opacity__opacity(0.9);', base=true},
	{'.backdrop-opacity-95', '__tw_backdrop_opacity__opacity(0.95);', base=true},
	{'.backdrop-opacity-100', '__tw_backdrop_opacity__opacity(1);', base=true},
}