return {
	{'.bg-opacity-0', '--tw-bg-opacity: 0;', base=true},
	{'.bg-opacity-5', '--tw-bg-opacity: 0.05;', base=true},
	{'.bg-opacity-10', '--tw-bg-opacity: 0.1;', base=true},
	{'.bg-opacity-20', '--tw-bg-opacity: 0.2;', base=true},
	{'.bg-opacity-25', '--tw-bg-opacity: 0.25;', base=true},
	{'.bg-opacity-30', '--tw-bg-opacity: 0.3;', base=true},
	{'.bg-opacity-40', '--tw-bg-opacity: 0.4;', base=true},
	{'.bg-opacity-50', '--tw-bg-opacity: 0.5;', base=true},
	{'.bg-opacity-60', '--tw-bg-opacity: 0.6;', base=true},
	{'.bg-opacity-70', '--tw-bg-opacity: 0.7;', base=true},
	{'.bg-opacity-75', '--tw-bg-opacity: 0.75;', base=true},
	{'.bg-opacity-80', '--tw-bg-opacity: 0.8;', base=true},
	{'.bg-opacity-90', '--tw-bg-opacity: 0.9;', base=true},
	{'.bg-opacity-95', '--tw-bg-opacity: 0.95;', base=true},
	{'.bg-opacity-100', '--tw-bg-opacity: 1;', base=true},
}