return {
	{'.backdrop-opacity-0', '--tw-backdrop-opacity: opacity(0);', base=true},
	{'.backdrop-opacity-5', '--tw-backdrop-opacity: opacity(0.05);', base=true},
	{'.backdrop-opacity-10', '--tw-backdrop-opacity: opacity(0.1);', base=true},
	{'.backdrop-opacity-20', '--tw-backdrop-opacity: opacity(0.2);', base=true},
	{'.backdrop-opacity-25', '--tw-backdrop-opacity: opacity(0.25);', base=true},
	{'.backdrop-opacity-30', '--tw-backdrop-opacity: opacity(0.3);', base=true},
	{'.backdrop-opacity-40', '--tw-backdrop-opacity: opacity(0.4);', base=true},
	{'.backdrop-opacity-50', '--tw-backdrop-opacity: opacity(0.5);', base=true},
	{'.backdrop-opacity-60', '--tw-backdrop-opacity: opacity(0.6);', base=true},
	{'.backdrop-opacity-70', '--tw-backdrop-opacity: opacity(0.7);', base=true},
	{'.backdrop-opacity-75', '--tw-backdrop-opacity: opacity(0.75);', base=true},
	{'.backdrop-opacity-80', '--tw-backdrop-opacity: opacity(0.8);', base=true},
	{'.backdrop-opacity-90', '--tw-backdrop-opacity: opacity(0.9);', base=true},
	{'.backdrop-opacity-95', '--tw-backdrop-opacity: opacity(0.95);', base=true},
	{'.backdrop-opacity-100', '--tw-backdrop-opacity: opacity(1);', base=true},
}