return {
	{'Layout', 'layout'},
	{'Spacing', 'spacing'},
	{'Backgrounds', 'backgrounds'},
	{'Tables', 'tables'},
	{'Transforms', 'transforms'},
	{'Effects', 'effects'},
	{'Flexbox', 'flexbox'},
	{'Sizing', 'sizing'},
	{'Borders', 'borders'},
	{'Transitions and Animation', 'transitions_and_animation'},
	{'Interactivity', 'interactivity'},
	{'SVG', 'svg'},
	{'Grid', 'grid'},
	{'Box Alignment', 'box_alignment'},
	{'Typography', 'typography'},
	{'Filter', 'filter'},
}