return {
	{'border-radius', 'border_radius', doc='https://tailwindcss.com/docs/border-radius'},
	{'border-width', 'border_width', doc='https://tailwindcss.com/docs/border-width'},
	{'border-color', 'border_color', doc='https://tailwindcss.com/docs/border-color'},
	{'border opacity', 'border_opacity', doc='https://tailwindcss.com/docs/border-opacity'},
	{'border-style', 'border_style', doc='https://tailwindcss.com/docs/border-style'},
	{'divide width', 'divide_width', doc='https://tailwindcss.com/docs/divide-width'},
	{'divide color', 'divide_color', doc='https://tailwindcss.com/docs/divide-color'},
	{'divide opacity', 'divide_opacity', doc='https://tailwindcss.com/docs/divide-opacity'},
	{'divide style', 'divide_style', doc='https://tailwindcss.com/docs/divide-style'},
	{'ring width', 'ring_width', doc='https://tailwindcss.com/docs/ring-width'},
	{'ring color', 'ring_color', doc='https://tailwindcss.com/docs/ring-color'},
	{'ring opacity', 'ring_opacity', doc='https://tailwindcss.com/docs/ring-opacity'},
	{'ring offset width', 'ring_offset_width', doc='https://tailwindcss.com/docs/ring-offset-width'},
	{'ring offset color', 'ring_offset_color', doc='https://tailwindcss.com/docs/ring-offset-color'},
}