return {
	{'.border', 'border-width: 1px;', base=true},
	{'.border-0', 'border-width: 0px;', base=true},
	{'.border-2', 'border-width: 2px;', base=true},
	{'.border-4', 'border-width: 4px;', base=true},
	{'.border-8', 'border-width: 8px;', base=true},
	{'.border-t', 'border-top-width: 1px;', base=true},
	{'.border-t-0', 'border-top-width: 0px;', base=true},
	{'.border-t-2', 'border-top-width: 2px;', base=true},
	{'.border-t-4', 'border-top-width: 4px;', base=true},
	{'.border-t-8', 'border-top-width: 8px;', base=true},
	{'.border-r', 'border-right-width: 1px;', base=true},
	{'.border-r-0', 'border-right-width: 0px;', base=true},
	{'.border-r-2', 'border-right-width: 2px;', base=true},
	{'.border-r-4', 'border-right-width: 4px;', base=true},
	{'.border-r-8', 'border-right-width: 8px;', base=true},
	{'.border-b', 'border-bottom-width: 1px;', base=true},
	{'.border-b-0', 'border-bottom-width: 0px;', base=true},
	{'.border-b-2', 'border-bottom-width: 2px;', base=true},
	{'.border-b-4', 'border-bottom-width: 4px;', base=true},
	{'.border-b-8', 'border-bottom-width: 8px;', base=true},
	{'.border-l', 'border-left-width: 1px;', base=true},
	{'.border-l-0', 'border-left-width: 0px;', base=true},
	{'.border-l-2', 'border-left-width: 2px;', base=true},
	{'.border-l-4', 'border-left-width: 4px;', base=true},
	{'.border-l-8', 'border-left-width: 8px;', base=true},
}