return {
	{'.border-opacity-0', '--tw-border-opacity: 0;', base=true},
	{'.border-opacity-5', '--tw-border-opacity: 0.05;', base=true},
	{'.border-opacity-10', '--tw-border-opacity: 0.1;', base=true},
	{'.border-opacity-20', '--tw-border-opacity: 0.2;', base=true},
	{'.border-opacity-25', '--tw-border-opacity: 0.25;', base=true},
	{'.border-opacity-30', '--tw-border-opacity: 0.3;', base=true},
	{'.border-opacity-40', '--tw-border-opacity: 0.4;', base=true},
	{'.border-opacity-50', '--tw-border-opacity: 0.5;', base=true},
	{'.border-opacity-60', '--tw-border-opacity: 0.6;', base=true},
	{'.border-opacity-70', '--tw-border-opacity: 0.7;', base=true},
	{'.border-opacity-75', '--tw-border-opacity: 0.75;', base=true},
	{'.border-opacity-80', '--tw-border-opacity: 0.8;', base=true},
	{'.border-opacity-90', '--tw-border-opacity: 0.9;', base=true},
	{'.border-opacity-95', '--tw-border-opacity: 0.95;', base=true},
	{'.border-opacity-100', '--tw-border-opacity: 1;', base=true},
}