return {
	{'border-radius', 'border_radius', doc='https://tailwindcss.com/docs/border-radius', desc='Sets border radius.'},
	{'border-width', 'border_width', doc='https://tailwindcss.com/docs/border-width', desc='Sets border width in increments of 1px.'},
	{'border-color', 'border_color', doc='https://tailwindcss.com/docs/border-color', desc='Sets border color.'},
	{'border opacity', 'border_opacity', doc='https://tailwindcss.com/docs/border-opacity', desc='Sets border opacity when used with border-[color].'},
	{'border-style', 'border_style', doc='https://tailwindcss.com/docs/border-style', desc='Sets border style.'},
	{'divide width', 'divide_width', doc='https://tailwindcss.com/docs/divide-width', desc='Sets left or top (x or y) border width between child elements, but skips the first element.'},
	{'divide color', 'divide_color', doc='https://tailwindcss.com/docs/divide-color', desc='Sets border color between child elements when using divide width.'},
	{'divide opacity', 'divide_opacity', doc='https://tailwindcss.com/docs/divide-opacity', desc='Sets border opacity between elements when used with divide-[color].'},
	{'divide style', 'divide_style', doc='https://tailwindcss.com/docs/divide-style', desc='Sets border style between elements when using divide width.'},
	{'ring width', 'ring_width', doc='https://tailwindcss.com/docs/ring-width', desc='Sets the width of outline rings using box shadows.'},
	{'ring color', 'ring_color', doc='https://tailwindcss.com/docs/ring-color', desc='Sets the color of the outline ring.'},
	{'ring opacity', 'ring_opacity', doc='https://tailwindcss.com/docs/ring-opacity', desc='Sets the opacity of the outline ring.'},
	{'ring offset width', 'ring_offset_width', doc='https://tailwindcss.com/docs/ring-offset-width', desc='Sets an offset for outline rings.'},
	{'ring offset color', 'ring_offset_color', doc='https://tailwindcss.com/docs/ring-offset-color', desc='Sets the color of the outline ring offset.'},
}