return {
	{'.border', 'border_width__1px;', base=true},
	{'.border-0', 'border_width__0px;', base=true},
	{'.border-2', 'border_width__2px;', base=true},
	{'.border-4', 'border_width__4px;', base=true},
	{'.border-8', 'border_width__8px;', base=true},
	{'.border-t', 'border_top_width__1px;', base=true},
	{'.border-t-0', 'border_top_width__0px;', base=true},
	{'.border-t-2', 'border_top_width__2px;', base=true},
	{'.border-t-4', 'border_top_width__4px;', base=true},
	{'.border-t-8', 'border_top_width__8px;', base=true},
	{'.border-r', 'border_right_width__1px;', base=true},
	{'.border-r-0', 'border_right_width__0px;', base=true},
	{'.border-r-2', 'border_right_width__2px;', base=true},
	{'.border-r-4', 'border_right_width__4px;', base=true},
	{'.border-r-8', 'border_right_width__8px;', base=true},
	{'.border-b', 'border_bottom_width__1px;', base=true},
	{'.border-b-0', 'border_bottom_width__0px;', base=true},
	{'.border-b-2', 'border_bottom_width__2px;', base=true},
	{'.border-b-4', 'border_bottom_width__4px;', base=true},
	{'.border-b-8', 'border_bottom_width__8px;', base=true},
	{'.border-l', 'border_left_width__1px;', base=true},
	{'.border-l-0', 'border_left_width__0px;', base=true},
	{'.border-l-2', 'border_left_width__2px;', base=true},
	{'.border-l-4', 'border_left_width__4px;', base=true},
	{'.border-l-8', 'border_left_width__8px;', base=true},
}