return {
	{'Breakpoints', 'breakpoints', doc='https://tailwindcss.com/docs/responsive-design', desc='Breakpoints (screen sizes) that wrap utility classes.'},
	{'box-decoration-break', 'box_decoration_break', doc='https://tailwindcss.com/docs/box-decoration-break', desc='Sets rendering of an element\'s fragments when broken across multiple lines, columns, or pages.'},
	{'container', 'container', doc='https://tailwindcss.com/docs/container', desc='Sets max-width to match min-width of the current breakpoint.'},
	{'box-sizing', 'box_sizing', doc='https://tailwindcss.com/docs/box-sizing', desc='Sets how the total width and height of an element is calculated.'},
	{'display', 'display', doc='https://tailwindcss.com/docs/display', desc='Sets the display box type of an element.'},
	{'float', 'float', doc='https://tailwindcss.com/docs/floats', desc='Sets an element\'s placement to a side of its container and allows content to wrap around it.'},
	{'clear', 'clear', doc='https://tailwindcss.com/docs/clear', desc='Sets whether an element is moved below preceding floated elements.'},
	{'isolation', 'isolation', doc='https://tailwindcss.com/docs/isolation', desc='Sets whether an element creates a stacking context.'},
	{'object-fit', 'object_fit', doc='https://tailwindcss.com/docs/object-fit', desc='Sets how the content of a replaced element (img or video tag) should be resized.'},
	{'object-position', 'object_position', doc='https://tailwindcss.com/docs/object-position', desc='Sets the alignment of the selected replaced element.'},
	{'overflow', 'overflow', doc='https://tailwindcss.com/docs/overflow', desc='Sets how to handle content that\'s too big for its container.'},
	{'overscroll', 'overscroll', doc='https://tailwindcss.com/docs/overscroll-behavior', desc='Sets browser behavior upon reaching the boundary of a scrolling area.'},
	{'position', 'position', doc='https://tailwindcss.com/docs/positioning', desc='Sets an element\'s position.'},
	{'top, right, bottom, left', 'top__right__bottom__left', doc='https://tailwindcss.com/docs/top-right-bottom-left', desc='Sets the placement of a positioned element.'},
	{'visibility', 'visibility', doc='https://tailwindcss.com/docs/visibility', desc='Show or hide without affecting the layout of the document.'},
	{'z-index', 'z_index', doc='https://tailwindcss.com/docs/z-index', desc='Sets the z-order ("stack order") of a positioned element.'},
	{'padding', 'padding', doc='https://tailwindcss.com/docs/padding', desc='Controls padding in 0.25rem increments.'},
	{'margin', 'margin', doc='https://tailwindcss.com/docs/margin', desc='Controls margin (and negative margin) in 0.25rem increments.'},
	{'space between', 'space_between', doc='https://tailwindcss.com/docs/space', desc='Sets left or top (x or y) margin between child elements, but skips the first element.'},
	{'background-attachment', 'background_attachment', doc='https://tailwindcss.com/docs/background-attachment', desc='Sets behavior of background images when scrolling.'},
	{'background-clip', 'background_clip', doc='https://tailwindcss.com/docs/background-clip', desc='Sets where a background extends.'},
	{'background-color', 'background_color', doc='https://tailwindcss.com/docs/background-color', desc='Sets background color.'},
	{'background opacity', 'background_opacity', doc='https://tailwindcss.com/docs/background-opacity', desc='Sets background opacity when used with bg-[color].'},
	{'background origin', 'background_origin', doc='https://tailwindcss.com/docs/background-origin', desc='Sets the background origin position.'},
	{'background-position', 'background_position', doc='https://tailwindcss.com/docs/background-position', desc='Sets position of a background image.'},
	{'background-repeat', 'background_repeat', doc='https://tailwindcss.com/docs/background-repeat', desc='Sets repetition of a background image.'},
	{'background-size', 'background_size', doc='https://tailwindcss.com/docs/background-size', desc='Sets background size of a background image.'},
	{'background-image', 'background_image', doc='https://tailwindcss.com/docs/background-image', desc='Sets background image.'},
	{'gradient color', 'gradient_color', doc='https://tailwindcss.com/docs/gradient-color-stops', desc='Sets the background color gradients and where to stop.'},
	{'border-collapse', 'border_collapse', doc='https://tailwindcss.com/docs/border-collapse', desc='Collapse or separate table borders.'},
	{'table-layout', 'table_layout', doc='https://tailwindcss.com/docs/table-layout', desc='Defines the algorithm used to lay out table cells, rows, and columns.'},
	{'scale', 'scale', doc='https://tailwindcss.com/docs/scale', desc='Scales an element that has transform applied.'},
	{'rotate', 'rotate', doc='https://tailwindcss.com/docs/rotate', desc='Rotates an element that has transform applied.'},
	{'translate', 'translate', doc='https://tailwindcss.com/docs/translate', desc='Translates an element that has transform applied.'},
	{'skew', 'skew', doc='https://tailwindcss.com/docs/skew', desc='Skews an element that has transform applied.'},
	{'transform-origin', 'transform_origin', doc='https://tailwindcss.com/docs/transform-origin', desc='Sets the origin of an element\'s transforms. Think of the origin as pushing a thumbtack into the element at the specified position.'},
	{'transform', 'transform', doc='https://tailwindcss.com/docs/transform', desc='Sets the transform of an element.'},
	{'box-shadow', 'box_shadow', doc='https://tailwindcss.com/docs/box-shadow', desc='Sets the shadow around an element.'},
	{'opacity', 'opacity', doc='https://tailwindcss.com/docs/opacity', desc='Sets the transparency of an element.'},
	{'mix-blend-mode', 'mix_blend_mode', doc='https://tailwindcss.com/docs/mix-blend-mode', desc='Sets how an element blends with the background.'},
	{'background-blend-mode', 'background_blend_mode', doc='https://tailwindcss.com/docs/background-blend-mode', desc='Sets how an element\'s background images blend with its background color.'},
	{'display', 'display', doc='https://tailwindcss.com/docs/display', desc='Sets element to be a flex container.'},
	{'flex-direction', 'flex_direction', doc='https://tailwindcss.com/docs/flexbox-direction', desc='Sets direction of flex items.'},
	{'flex-wrap', 'flex_wrap', doc='https://tailwindcss.com/docs/flexbox-wrapping', desc='Creates how flex items wrap.'},
	{'flex', 'flex', doc='https://tailwindcss.com/docs/flex', desc='Controls how flex items grow and shrink.'},
	{'flex-grow', 'flex_grow', doc='https://tailwindcss.com/docs/flex-grow', desc='Controls how flex items grow.'},
	{'flex-shrink', 'flex_shrink', doc='https://tailwindcss.com/docs/flex-shrink', desc='Controls how flex items shrink.'},
	{'order', 'order', doc='https://tailwindcss.com/docs/order', desc='Controls how flex items are ordered.'},
	{'width', 'width', doc='https://tailwindcss.com/docs/width', desc='Sets the width of an element.'},
	{'min-width', 'min_width', doc='https://tailwindcss.com/docs/min-width', desc='Sets the minimum width of an element.'},
	{'max-width', 'max_width', doc='https://tailwindcss.com/docs/max-width', desc='Sets the maxiumum width of an element.'},
	{'height', 'height', doc='https://tailwindcss.com/docs/height', desc='Sets the height of an element.'},
	{'min-height', 'min_height', doc='https://tailwindcss.com/docs/min-height', desc='Sets the minimum height of an element.'},
	{'max-height', 'max_height', doc='https://tailwindcss.com/docs/max-height', desc='Sets the maxiumum height of an element.'},
	{'border-radius', 'border_radius', doc='https://tailwindcss.com/docs/border-radius', desc='Sets border radius.'},
	{'border-width', 'border_width', doc='https://tailwindcss.com/docs/border-width', desc='Sets border width in increments of 1px.'},
	{'border-color', 'border_color', doc='https://tailwindcss.com/docs/border-color', desc='Sets border color.'},
	{'border opacity', 'border_opacity', doc='https://tailwindcss.com/docs/border-opacity', desc='Sets border opacity when used with border-[color].'},
	{'border-style', 'border_style', doc='https://tailwindcss.com/docs/border-style', desc='Sets border style.'},
	{'divide width', 'divide_width', doc='https://tailwindcss.com/docs/divide-width', desc='Sets left or top (x or y) border width between child elements, but skips the first element.'},
	{'divide color', 'divide_color', doc='https://tailwindcss.com/docs/divide-color', desc='Sets border color between child elements when using divide width.'},
	{'divide opacity', 'divide_opacity', doc='https://tailwindcss.com/docs/divide-opacity', desc='Sets border opacity between elements when used with divide-[color].'},
	{'divide style', 'divide_style', doc='https://tailwindcss.com/docs/divide-style', desc='Sets border style between elements when using divide width.'},
	{'ring width', 'ring_width', doc='https://tailwindcss.com/docs/ring-width', desc='Sets the width of outline rings using box shadows.'},
	{'ring color', 'ring_color', doc='https://tailwindcss.com/docs/ring-color', desc='Sets the color of the outline ring.'},
	{'ring opacity', 'ring_opacity', doc='https://tailwindcss.com/docs/ring-opacity', desc='Sets the opacity of the outline ring.'},
	{'ring offset width', 'ring_offset_width', doc='https://tailwindcss.com/docs/ring-offset-width', desc='Sets an offset for outline rings.'},
	{'ring offset color', 'ring_offset_color', doc='https://tailwindcss.com/docs/ring-offset-color', desc='Sets the color of the outline ring offset.'},
	{'transition-property', 'transition_property', doc='https://tailwindcss.com/docs/transition-property', desc='Sets the CSS properties affected by transition animations.'},
	{'transition-duration', 'transition_duration', doc='https://tailwindcss.com/docs/transition-duration', desc='Sets the length of time for a transition animations to complete.'},
	{'transition-timing-function', 'transition_timing_function', doc='https://tailwindcss.com/docs/transition-timing-function', desc='Sets the easing function of transition animations.'},
	{'transition-delay', 'transition_delay', doc='https://tailwindcss.com/docs/transition-delay', desc='Sets the delay for transitions.'},
	{'animation', 'animation', doc='https://tailwindcss.com/docs/animation', desc='Sets CSS animations.'},
	{'appearance', 'appearance', doc='https://tailwindcss.com/docs/appearance', desc='Disables native styling based on the operating system\'s theme.'},
	{'cursor', 'cursor', doc='https://tailwindcss.com/docs/cursor', desc='Changes the cursor when hovering over an element.'},
	{'outline', 'outline', doc='https://tailwindcss.com/docs/outline', desc='Sets the outline of the element.'},
	{'pointer-events', 'pointer_events', doc='https://tailwindcss.com/docs/pointer-events', desc='Specifies whether an element is the target of mouse events.'},
	{'resize', 'resize', doc='https://tailwindcss.com/docs/resize', desc='Sets whether an element is resizable, along with direction.'},
	{'user-select', 'user_select', doc='https://tailwindcss.com/docs/user-select', desc='Controls whether the user can select text.'},
	{'accessibility', 'accessibility', doc='https://tailwindcss.com/docs/screen-readers/', desc='Controls whether an element is visually hidden but still accessible to screen readers.'},
	{'fill', 'fill', doc='https://tailwindcss.com/docs/fill', desc='Sets the color to paint an SVG.'},
	{'stroke', 'stroke', doc='https://tailwindcss.com/docs/stroke', desc='Sets the outline color of an SVG.'},
	{'stroke-width', 'stroke_width', doc='https://tailwindcss.com/docs/stroke-width', desc='Sets the outline width of an SVG.'},
	{'grid-template-columns', 'grid_template_columns', doc='https://tailwindcss.com/docs/grid-template-columns', desc='Defines columns for grid layout.'},
	{'grid-column, start/end', 'grid_column__start_end', doc='https://tailwindcss.com/docs/grid-column', desc='Sets a grid item size and location within the grid column.'},
	{'grid-template-rows', 'grid_template_rows', doc='https://tailwindcss.com/docs/grid-template-rows', desc='Defines rows for grid layout.'},
	{'grid-row, start/end', 'grid_row__start_end', doc='https://tailwindcss.com/docs/grid-row', desc='Sets a grid item size and location within the grid row.'},
	{'grid-auto-flow', 'grid_auto_flow', doc='https://tailwindcss.com/docs/grid-auto-flow', desc='Controls the auto placement of grid elements.'},
	{'grid-auto-columns', 'grid_auto_columns', doc='https://tailwindcss.com/docs/grid-auto-columns', desc='Controls the size of auto-generated (implicit) grid columns.'},
	{'grid-auto-rows', 'grid_auto_rows', doc='https://tailwindcss.com/docs/grid-auto-rows', desc='Controls the size of auto-generated (implicit) grid rows.'},
	{'gap', 'gap', doc='https://tailwindcss.com/docs/gap', desc='Sets the gaps (gutters) between rows and columns.'},
	{'justify-content', 'justify_content', doc='https://tailwindcss.com/docs/justify-content', desc='Controls how flex items are positioned along container\'s main axis.'},
	{'justify-items', 'justify_items', doc='https://tailwindcss.com/docs/justify-items', desc='Controls default alignment for items on the inline axis for grids.'},
	{'justify-self', 'justify_self', doc='https://tailwindcss.com/docs/justify-self', desc='Controls element alignment on the inline axis for a grid item.'},
	{'align-content', 'align_content', doc='https://tailwindcss.com/docs/align-content', desc='Controls how lines are positioned in multi-line flex containers.'},
	{'align-items', 'align_items', doc='https://tailwindcss.com/docs/align-items', desc='Sets flex items position along a contrainer\'s cross axis.'},
	{'align-self', 'align_self', doc='https://tailwindcss.com/docs/align-self', desc='Controls how an individual flex item is positioned along container\'s cross axis.'},
	{'place-content', 'place_content', doc='https://tailwindcss.com/docs/place-content', desc='Controls alignment in both directions at once for grid or flexbox.'},
	{'place-items', 'place_items', doc='https://tailwindcss.com/docs/place-items', desc='Controls alignment of items in both directions at once for grid or flexbox.'},
	{'place-self', 'place_self', doc='https://tailwindcss.com/docs/place-self', desc='Controls alignment of individual element in both directions at once for grid or flexbox.'},
	{'text color', 'text_color', doc='https://tailwindcss.com/docs/text-color', desc='Sets the text color.'},
	{'text opacity', 'text_opacity', doc='https://tailwindcss.com/docs/text-color', desc='Sets text opacity when used with text-[color].'},
	{'font-family', 'font_family', doc='https://tailwindcss.com/docs/fonts', desc='Sets the font family.'},
	{'font-size', 'font_size', doc='https://tailwindcss.com/docs/text-sizing', desc='Sets the font size.'},
	{'font-smoothing', 'font_smoothing', doc='https://tailwindcss.com/docs/text-style', desc='Sets the antialiasing of the font.'},
	{'font-style', 'font_style', doc='https://tailwindcss.com/docs/text-style', desc='Sets the style of the font.'},
	{'font-weight', 'font_weight', doc='https://tailwindcss.com/docs/font-weight', desc='Sets the font weight.'},
	{'font-variant-numeric', 'font_variant_numeric', doc='https://tailwindcss.com/docs/font-variant-numeric', desc='Sets the font number variant.'},
	{'letter-spacing', 'letter_spacing', doc='https://tailwindcss.com/docs/letter-spacing', desc='Sets the spacing between letters.'},
	{'line-height', 'line_height', doc='https://tailwindcss.com/docs/line-height', desc='Sets the line height.'},
	{'list-style-type', 'list_style_type', doc='https://tailwindcss.com/docs/list-style-type', desc='Sets the bullet style of a list.'},
	{'list-style-position', 'list_style_position', doc='https://tailwindcss.com/docs/list-style-position', desc='Sets the position of a list\'s bullets.'},
	{'::placeholder color', '__placeholder_color', doc='https://tailwindcss.com/docs/placeholder-color', desc='Sets the placeholder color using the ::placeholder pseudo element.'},
	{'::placeholder opacity', '__placeholder_opacity', doc='https://tailwindcss.com/docs/placeholder-opacity', desc='Sets the placeholder opacity when used with placeholder-[color].'},
	{'text-align', 'text_align', doc='https://tailwindcss.com/docs/text-alignment', desc='Sets the alignment of text.'},
	{'text-decoration', 'text_decoration', doc='https://tailwindcss.com/docs/text-decoration', desc='Sets the text-decoration of an element.'},
	{'text-transform', 'text_transform', doc='https://tailwindcss.com/docs/text-transform', desc='Sets the capitalization of text.'},
	{'text-overflow', 'text_overflow', doc='https://tailwindcss.com/docs/text-overflow', desc='Sets the overflow of text.'},
	{'vertical-align', 'vertical_align', doc='https://tailwindcss.com/docs/vertical-alignment', desc='Sets the vertical alignment of an inline or table-cell box.'},
	{'white-space', 'white_space', doc='https://tailwindcss.com/docs/whitespace', desc='Sets the whitespace of an element.'},
	{'word-break', 'word_break', doc='https://tailwindcss.com/docs/word-break', desc='Sets the word breaks of an element.'},
	{'filter', 'filter', doc='https://tailwindcss.com/docs/filter', desc='Sets filter on elements.'},
	{'blur', 'blur', doc='https://tailwindcss.com/docs/blur', desc='Sets blur filter on elements (use with filter utility).'},
	{'brightness', 'brightness', doc='https://tailwindcss.com/docs/brightness', desc='Sets brightness filter on elements (use with filter utility).'},
	{'contrast', 'contrast', doc='https://tailwindcss.com/docs/contrast', desc='Sets contrast filter on elements (use with filter utility).'},
	{'drop-shadow', 'drop_shadow', doc='https://tailwindcss.com/docs/drop-shadow', desc='Sets drop-shadow filter on elements (use with filter utility).'},
	{'grayscale', 'grayscale', doc='https://tailwindcss.com/docs/grayscale', desc='Sets grayscale filter on elements (use with filter utility).'},
	{'hue-rotate', 'hue_rotate', doc='https://tailwindcss.com/docs/hue-rotate', desc='Sets hue-rotate filter on elements (use with filter utility).'},
	{'invert', 'invert', doc='https://tailwindcss.com/docs/invert', desc='Sets invert filter on elements (use with filter utility).'},
	{'saturate', 'saturate', doc='https://tailwindcss.com/docs/saturate', desc='Sets saturate filter on elements (use with filter utility).'},
	{'sepia', 'sepia', doc='https://tailwindcss.com/docs/sepia', desc='Sets sepia filter on elements (use with filter utility).'},
	{'backdrop-filter', 'backdrop_filter', doc='https://tailwindcss.com/docs/backdrop-filter', desc='Sets backdrop filter filter on elements (use with filter utility).'},
	{'backdrop-blur', 'backdrop_blur', doc='https://tailwindcss.com/docs/backdrop-blur', desc='Sets backdrop blur filter on elements (use with filter utility).'},
	{'backdrop-brightness', 'backdrop_brightness', doc='https://tailwindcss.com/docs/backdrop-brightness', desc='Sets backdrop brightness filter on elements (use with filter utility).'},
	{'backdrop-contrast', 'backdrop_contrast', doc='https://tailwindcss.com/docs/backdrop-contrast', desc='Sets backdrop contrast filter on elements (use with filter utility).'},
	{'backdrop-grayscale', 'backdrop_grayscale', doc='https://tailwindcss.com/docs/backdrop-grayscale', desc='Sets backdrop grayscale filter on elements (use with filter utility).'},
	{'backdrop-hue-rotate', 'backdrop_hue_rotate', doc='https://tailwindcss.com/docs/backdrop-hue-rotate', desc='Sets backdrop hue-rotate filter on elements (use with filter utility).'},
	{'backdrop-invert', 'backdrop_invert', doc='https://tailwindcss.com/docs/backdrop-invert', desc='Sets backdrop invert filter on elements (use with filter utility).'},
	{'backdrop-opacity', 'backdrop_opacity', doc='https://tailwindcss.com/docs/backdrop-opacity', desc='Sets backdrop opacity filter on elements (use with filter utility).'},
	{'backdrop-saturate', 'backdrop_saturate', doc='https://tailwindcss.com/docs/backdrop-saturate', desc='Sets backdrop saturate filter on elements (use with filter utility).'},
	{'backdrop-sepia', 'backdrop_sepia', doc='https://tailwindcss.com/docs/backdrop-sepia', desc='Sets backdrop sepia filter on elements (use with filter utility).'},
}