return {
	{'.divide-opacity-0 > *', '--tw-divide-opacity: 0;', base=true},
	{'.divide-opacity-5 > *', '--tw-divide-opacity: 0.05;', base=true},
	{'.divide-opacity-10 > *', '--tw-divide-opacity: 0.1;', base=true},
	{'.divide-opacity-20 > *', '--tw-divide-opacity: 0.2;', base=true},
	{'.divide-opacity-25 > *', '--tw-divide-opacity: 0.25;', base=true},
	{'.divide-opacity-30 > *', '--tw-divide-opacity: 0.3;', base=true},
	{'.divide-opacity-40 > *', '--tw-divide-opacity: 0.4;', base=true},
	{'.divide-opacity-50 > *', '--tw-divide-opacity: 0.5;', base=true},
	{'.divide-opacity-60 > *', '--tw-divide-opacity: 0.6;', base=true},
	{'.divide-opacity-70 > *', '--tw-divide-opacity: 0.7;', base=true},
	{'.divide-opacity-75 > *', '--tw-divide-opacity: 0.75;', base=true},
	{'.divide-opacity-80 > *', '--tw-divide-opacity: 0.8;', base=true},
	{'.divide-opacity-90 > *', '--tw-divide-opacity: 0.9;', base=true},
	{'.divide-opacity-95 > *', '--tw-divide-opacity: 0.95;', base=true},
	{'.divide-opacity-100 > *', '--tw-divide-opacity: 1;', base=true},
}