return {
	{'filter', 'filter', doc='https://tailwindcss.com/docs/filter'},
	{'blur', 'blur', doc='https://tailwindcss.com/docs/blur'},
	{'brightness', 'brightness', doc='https://tailwindcss.com/docs/brightness'},
	{'contrast', 'contrast', doc='https://tailwindcss.com/docs/contrast'},
	{'drop-shadow', 'drop_shadow', doc='https://tailwindcss.com/docs/drop-shadow'},
	{'grayscale', 'grayscale', doc='https://tailwindcss.com/docs/grayscale'},
	{'hue-rotate', 'hue_rotate', doc='https://tailwindcss.com/docs/hue-rotate'},
	{'invert', 'invert', doc='https://tailwindcss.com/docs/invert'},
	{'saturate', 'saturate', doc='https://tailwindcss.com/docs/saturate'},
	{'sepia', 'sepia', doc='https://tailwindcss.com/docs/sepia'},
	{'backdrop-filter', 'backdrop_filter', doc='https://tailwindcss.com/docs/backdrop-filter'},
	{'backdrop-blur', 'backdrop_blur', doc='https://tailwindcss.com/docs/backdrop-blur'},
	{'backdrop-brightness', 'backdrop_brightness', doc='https://tailwindcss.com/docs/backdrop-brightness'},
	{'backdrop-contrast', 'backdrop_contrast', doc='https://tailwindcss.com/docs/backdrop-contrast'},
	{'backdrop-grayscale', 'backdrop_grayscale', doc='https://tailwindcss.com/docs/backdrop-grayscale'},
	{'backdrop-hue-rotate', 'backdrop_hue_rotate', doc='https://tailwindcss.com/docs/backdrop-hue-rotate'},
	{'backdrop-invert', 'backdrop_invert', doc='https://tailwindcss.com/docs/backdrop-invert'},
	{'backdrop-opacity', 'backdrop_opacity', doc='https://tailwindcss.com/docs/backdrop-opacity'},
	{'backdrop-saturate', 'backdrop_saturate', doc='https://tailwindcss.com/docs/backdrop-saturate'},
	{'backdrop-sepia', 'backdrop_sepia', doc='https://tailwindcss.com/docs/backdrop-sepia'},
}