return {
	{'filter', 'filter', doc='https://tailwindcss.com/docs/filter', desc='Sets filter on elements.'},
	{'blur', 'blur', doc='https://tailwindcss.com/docs/blur', desc='Sets blur filter on elements (use with filter utility).'},
	{'brightness', 'brightness', doc='https://tailwindcss.com/docs/brightness', desc='Sets brightness filter on elements (use with filter utility).'},
	{'contrast', 'contrast', doc='https://tailwindcss.com/docs/contrast', desc='Sets contrast filter on elements (use with filter utility).'},
	{'drop-shadow', 'drop_shadow', doc='https://tailwindcss.com/docs/drop-shadow', desc='Sets drop-shadow filter on elements (use with filter utility).'},
	{'grayscale', 'grayscale', doc='https://tailwindcss.com/docs/grayscale', desc='Sets grayscale filter on elements (use with filter utility).'},
	{'hue-rotate', 'hue_rotate', doc='https://tailwindcss.com/docs/hue-rotate', desc='Sets hue-rotate filter on elements (use with filter utility).'},
	{'invert', 'invert', doc='https://tailwindcss.com/docs/invert', desc='Sets invert filter on elements (use with filter utility).'},
	{'saturate', 'saturate', doc='https://tailwindcss.com/docs/saturate', desc='Sets saturate filter on elements (use with filter utility).'},
	{'sepia', 'sepia', doc='https://tailwindcss.com/docs/sepia', desc='Sets sepia filter on elements (use with filter utility).'},
	{'backdrop-filter', 'backdrop_filter', doc='https://tailwindcss.com/docs/backdrop-filter', desc='Sets backdrop filter filter on elements (use with filter utility).'},
	{'backdrop-blur', 'backdrop_blur', doc='https://tailwindcss.com/docs/backdrop-blur', desc='Sets backdrop blur filter on elements (use with filter utility).'},
	{'backdrop-brightness', 'backdrop_brightness', doc='https://tailwindcss.com/docs/backdrop-brightness', desc='Sets backdrop brightness filter on elements (use with filter utility).'},
	{'backdrop-contrast', 'backdrop_contrast', doc='https://tailwindcss.com/docs/backdrop-contrast', desc='Sets backdrop contrast filter on elements (use with filter utility).'},
	{'backdrop-grayscale', 'backdrop_grayscale', doc='https://tailwindcss.com/docs/backdrop-grayscale', desc='Sets backdrop grayscale filter on elements (use with filter utility).'},
	{'backdrop-hue-rotate', 'backdrop_hue_rotate', doc='https://tailwindcss.com/docs/backdrop-hue-rotate', desc='Sets backdrop hue-rotate filter on elements (use with filter utility).'},
	{'backdrop-invert', 'backdrop_invert', doc='https://tailwindcss.com/docs/backdrop-invert', desc='Sets backdrop invert filter on elements (use with filter utility).'},
	{'backdrop-opacity', 'backdrop_opacity', doc='https://tailwindcss.com/docs/backdrop-opacity', desc='Sets backdrop opacity filter on elements (use with filter utility).'},
	{'backdrop-saturate', 'backdrop_saturate', doc='https://tailwindcss.com/docs/backdrop-saturate', desc='Sets backdrop saturate filter on elements (use with filter utility).'},
	{'backdrop-sepia', 'backdrop_sepia', doc='https://tailwindcss.com/docs/backdrop-sepia', desc='Sets backdrop sepia filter on elements (use with filter utility).'},
}