return {
	{'.text-xs', 'font-size: 0.75rem;|line-height: 1rem;	12px', base=true},
	{'.text-sm', 'font-size: 0.875rem;|line-height: 1.25rem;	14px', base=true},
	{'.text-base', 'font-size: 1rem;|line-height: 1.5rem;	16px', base=true},
	{'.text-lg', 'font-size: 1.125rem;|line-height: 1.75rem;	18px', base=true},
	{'.text-xl', 'font-size: 1.25rem;|line-height: 1.75rem;	20px', base=true},
	{'.text-2xl', 'font-size: 1.5rem;|line-height: 2rem;	24px', base=true},
	{'.text-3xl', 'font-size: 1.875rem;|line-height: 2.25rem;	30px', base=true},
	{'.text-4xl', 'font-size: 2.25rem;|line-height: 2.5rem;	36px', base=true},
	{'.text-5xl', 'font-size: 3rem;|line-height: 1;	48px', base=true},
	{'.text-6xl', 'font-size: 3.75rem;|line-height: 1;	60px', base=true},
	{'.text-7xl', 'font-size: 4.5rem;|line-height: 1;	72px', base=true},
	{'.text-8xl', 'font-size: 6rem;|line-height: 1;	96px', base=true},
	{'.text-9xl', 'font-size: 8rem;|line-height: 1;	128px', base=true},
}