return {
	{'.text-xs', 'font_size__0.75rem; line_height__1rem;	12px', base=true},
	{'.text-sm', 'font_size__0.875rem; line_height__1.25rem;	14px', base=true},
	{'.text-base', 'font_size__1rem; line_height__1.5rem;	16px', base=true},
	{'.text-lg', 'font_size__1.125rem; line_height__1.75rem;	18px', base=true},
	{'.text-xl', 'font_size__1.25rem; line_height__1.75rem;	20px', base=true},
	{'.text-2xl', 'font_size__1.5rem; line_height__2rem;	24px', base=true},
	{'.text-3xl', 'font_size__1.875rem; line_height__2.25rem;	30px', base=true},
	{'.text-4xl', 'font_size__2.25rem; line_height__2.5rem;	36px', base=true},
	{'.text-5xl', 'font_size__3rem; line_height__1;	48px', base=true},
	{'.text-6xl', 'font_size__3.75rem; line_height__1;	60px', base=true},
	{'.text-7xl', 'font_size__4.5rem; line_height__1;	72px', base=true},
	{'.text-8xl', 'font_size__6rem; line_height__1;	96px', base=true},
	{'.text-9xl', 'font_size__8rem; line_height__1;	128px', base=true},
}