return {
	{'.row-auto', 'grid-row: auto;', base=true},
	{'.row-span-1', 'grid-row: span 1 / span 1;', base=true},
	{'.row-span-2', 'grid-row: span 2 / span 2;', base=true},
	{'.row-span-3', 'grid-row: span 3 / span 3;', base=true},
	{'.row-span-4', 'grid-row: span 4 / span 4;', base=true},
	{'.row-span-5', 'grid-row: span 5 / span 5;', base=true},
	{'.row-span-6', 'grid-row: span 6 / span 6;', base=true},
	{'.row-span-full', 'grid-row: 1 / -1;', base=true},
	{'.row-start-1', 'grid-row-start: 1;', base=true},
	{'.row-start-2', 'grid-row-start: 2;', base=true},
	{'.row-start-3', 'grid-row-start: 3;', base=true},
	{'.row-start-4', 'grid-row-start: 4;', base=true},
	{'.row-start-5', 'grid-row-start: 5;', base=true},
	{'.row-start-6', 'grid-row-start: 6;', base=true},
	{'.row-start-7', 'grid-row-start: 7;', base=true},
	{'.row-start-auto', 'grid-row-start: auto;', base=true},
	{'.row-end-1', 'grid-row-end: 1;', base=true},
	{'.row-end-2', 'grid-row-end: 2;', base=true},
	{'.row-end-3', 'grid-row-end: 3;', base=true},
	{'.row-end-4', 'grid-row-end: 4;', base=true},
	{'.row-end-5', 'grid-row-end: 5;', base=true},
	{'.row-end-6', 'grid-row-end: 6;', base=true},
	{'.row-end-7', 'grid-row-end: 7;', base=true},
	{'.row-end-auto', 'grid-row-end: auto;', base=true},
}