return {
	{'.row-auto', 'grid_row__auto;', base=true},
	{'.row-span-1', 'grid_row__span_1___span_1;', base=true},
	{'.row-span-2', 'grid_row__span_2___span_2;', base=true},
	{'.row-span-3', 'grid_row__span_3___span_3;', base=true},
	{'.row-span-4', 'grid_row__span_4___span_4;', base=true},
	{'.row-span-5', 'grid_row__span_5___span_5;', base=true},
	{'.row-span-6', 'grid_row__span_6___span_6;', base=true},
	{'.row-span-full', 'grid_row__1____1;', base=true},
	{'.row-start-1', 'grid_row_start__1;', base=true},
	{'.row-start-2', 'grid_row_start__2;', base=true},
	{'.row-start-3', 'grid_row_start__3;', base=true},
	{'.row-start-4', 'grid_row_start__4;', base=true},
	{'.row-start-5', 'grid_row_start__5;', base=true},
	{'.row-start-6', 'grid_row_start__6;', base=true},
	{'.row-start-7', 'grid_row_start__7;', base=true},
	{'.row-start-auto', 'grid_row_start__auto;', base=true},
	{'.row-end-1', 'grid_row_end__1;', base=true},
	{'.row-end-2', 'grid_row_end__2;', base=true},
	{'.row-end-3', 'grid_row_end__3;', base=true},
	{'.row-end-4', 'grid_row_end__4;', base=true},
	{'.row-end-5', 'grid_row_end__5;', base=true},
	{'.row-end-6', 'grid_row_end__6;', base=true},
	{'.row-end-7', 'grid_row_end__7;', base=true},
	{'.row-end-auto', 'grid_row_end__auto;', base=true},
}