return {
	{'Breakpoints', 'breakpoints', doc='https://tailwindcss.com/docs/responsive-design', desc='Breakpoints (screen sizes) that wrap utility classes.'},
	{'box-decoration-break', 'box_decoration_break', doc='https://tailwindcss.com/docs/box-decoration-break', desc='Sets rendering of an element\'s fragments when broken across multiple lines, columns, or pages.'},
	{'container', 'container', doc='https://tailwindcss.com/docs/container', desc='Sets max-width to match min-width of the current breakpoint.'},
	{'box-sizing', 'box_sizing', doc='https://tailwindcss.com/docs/box-sizing', desc='Sets how the total width and height of an element is calculated.'},
	{'display', 'display', doc='https://tailwindcss.com/docs/display', desc='Sets the display box type of an element.'},
	{'float', 'float', doc='https://tailwindcss.com/docs/floats', desc='Sets an element\'s placement to a side of its container and allows content to wrap around it.'},
	{'clear', 'clear', doc='https://tailwindcss.com/docs/clear', desc='Sets whether an element is moved below preceding floated elements.'},
	{'isolation', 'isolation', doc='https://tailwindcss.com/docs/isolation', desc='Sets whether an element creates a stacking context.'},
	{'object-fit', 'object_fit', doc='https://tailwindcss.com/docs/object-fit', desc='Sets how the content of a replaced element (img or video tag) should be resized.'},
	{'object-position', 'object_position', doc='https://tailwindcss.com/docs/object-position', desc='Sets the alignment of the selected replaced element.'},
	{'overflow', 'overflow', doc='https://tailwindcss.com/docs/overflow', desc='Sets how to handle content that\'s too big for its container.'},
	{'overscroll', 'overscroll', doc='https://tailwindcss.com/docs/overscroll-behavior', desc='Sets browser behavior upon reaching the boundary of a scrolling area.'},
	{'position', 'position', doc='https://tailwindcss.com/docs/positioning', desc='Sets an element\'s position.'},
	{'top, right, bottom, left', 'top__right__bottom__left', doc='https://tailwindcss.com/docs/top-right-bottom-left', desc='Sets the placement of a positioned element.'},
	{'visibility', 'visibility', doc='https://tailwindcss.com/docs/visibility', desc='Show or hide without affecting the layout of the document.'},
	{'z-index', 'z_index', doc='https://tailwindcss.com/docs/z-index', desc='Sets the z-order ("stack order") of a positioned element.'},
}