return {
	{'Breakpoints', 'breakpoints', doc='https://tailwindcss.com/docs/responsive-design'},
	{'box-decoration-break', 'box_decoration_break', doc='https://tailwindcss.com/docs/box-decoration-break'},
	{'container', 'container', doc='https://tailwindcss.com/docs/container'},
	{'box-sizing', 'box_sizing', doc='https://tailwindcss.com/docs/box-sizing'},
	{'display', 'display', doc='https://tailwindcss.com/docs/display'},
	{'float', 'float', doc='https://tailwindcss.com/docs/floats'},
	{'clear', 'clear', doc='https://tailwindcss.com/docs/clear'},
	{'isolation', 'isolation', doc='https://tailwindcss.com/docs/isolation'},
	{'object-fit', 'object_fit', doc='https://tailwindcss.com/docs/object-fit'},
	{'object-position', 'object_position', doc='https://tailwindcss.com/docs/object-position'},
	{'overflow', 'overflow', doc='https://tailwindcss.com/docs/overflow'},
	{'overscroll', 'overscroll', doc='https://tailwindcss.com/docs/overscroll-behavior'},
	{'position', 'position', doc='https://tailwindcss.com/docs/positioning'},
	{'top, right, bottom, left', 'top__right__bottom__left', doc='https://tailwindcss.com/docs/top-right-bottom-left'},
	{'visibility', 'visibility', doc='https://tailwindcss.com/docs/visibility'},
	{'z-index', 'z_index', doc='https://tailwindcss.com/docs/z-index'},
}