return {
	{'.leading-none', 'line-height: 1;', base=true},
	{'.leading-tight', 'line-height: 1.25;', base=true},
	{'.leading-snug', 'line-height: 1.375;', base=true},
	{'.leading-normal', 'line-height: 1.5;', base=true},
	{'.leading-relaxed', 'line-height: 1.625;', base=true},
	{'.leading-loose', 'line-height: 2;', base=true},
	{'.leading-3', 'line-height: .75rem;	12px', base=true},
	{'.leading-4', 'line-height: 1rem;	16px', base=true},
	{'.leading-5', 'line-height: 1.25rem;	20px', base=true},
	{'.leading-6', 'line-height: 1.5rem;	24px', base=true},
	{'.leading-7', 'line-height: 1.75rem;	28px', base=true},
	{'.leading-8', 'line-height: 2rem;	32px', base=true},
	{'.leading-9', 'line-height: 2.25rem;	36px', base=true},
	{'.leading-10', 'line-height: 2.5rem;	40px', base=true},
}