return {
	{'.leading-none', 'line_height__1;', base=true},
	{'.leading-tight', 'line_height__1.25;', base=true},
	{'.leading-snug', 'line_height__1.375;', base=true},
	{'.leading-normal', 'line_height__1.5;', base=true},
	{'.leading-relaxed', 'line_height__1.625;', base=true},
	{'.leading-loose', 'line_height__2;', base=true},
	{'.leading-3', 'line_height__.75rem;	12px', base=true},
	{'.leading-4', 'line_height__1rem;	16px', base=true},
	{'.leading-5', 'line_height__1.25rem;	20px', base=true},
	{'.leading-6', 'line_height__1.5rem;	24px', base=true},
	{'.leading-7', 'line_height__1.75rem;	28px', base=true},
	{'.leading-8', 'line_height__2rem;	32px', base=true},
	{'.leading-9', 'line_height__2.25rem;	36px', base=true},
	{'.leading-10', 'line_height__2.5rem;	40px', base=true},
}