return {
	{'.m-0', 'margin__0px;', base=true, fn=paste},
	{'.m-1', 'margin__0.25rem;	4px', base=true, fn=paste},
	{'.m-2', 'margin__0.5rem;	8px', base=true, fn=paste},
	{'.m-3', 'margin__0.75rem;	12px', base=true, fn=paste},
	{'.m-4', 'margin__1rem;	16px', base=true, fn=paste},
	{'.m-5', 'margin__1.25rem;	20px', base=true, fn=paste},
	{'.m-6', 'margin__1.5rem;	24px', base=true, fn=paste},
	{'.m-7', 'margin__1.75rem;	28px', base=true, fn=paste},
	{'.m-8', 'margin__2rem;	32px', base=true, fn=paste},
	{'.m-9', 'margin__2.25rem;	36px', base=true, fn=paste},
	{'.m-10', 'margin__2.5rem;	40px', base=true, fn=paste},
	{'.m-11', 'margin__2.75rem;	44px', base=true, fn=paste},
	{'.m-12', 'margin__3rem;	48px', base=true, fn=paste},
	{'.m-14', 'margin__3.5rem;	56px', base=true, fn=paste},
	{'.m-16', 'margin__4rem;	64px', base=true, fn=paste},
	{'.m-20', 'margin__5rem;	80px', base=true, fn=paste},
	{'.m-24', 'margin__6rem;	96px', base=true, fn=paste},
	{'.m-28', 'margin__7rem;	112px', base=true, fn=paste},
	{'.m-32', 'margin__8rem;	128px', base=true, fn=paste},
	{'.m-36', 'margin__9rem;	144px', base=true, fn=paste},
	{'.m-40', 'margin__10rem;	160px', base=true, fn=paste},
	{'.m-44', 'margin__11rem;	176px', base=true, fn=paste},
	{'.m-48', 'margin__12rem;	192px', base=true, fn=paste},
	{'.m-52', 'margin__13rem;	208px', base=true, fn=paste},
	{'.m-56', 'margin__14rem;	224px', base=true, fn=paste},
	{'.m-60', 'margin__15rem;	240px', base=true, fn=paste},
	{'.m-64', 'margin__16rem;	256px', base=true, fn=paste},
	{'.m-72', 'margin__18rem;	288px', base=true, fn=paste},
	{'.m-80', 'margin__20rem;	320px', base=true, fn=paste},
	{'.m-96', 'margin__24rem;	384px', base=true, fn=paste},
	{'.m-auto', 'margin__auto;', base=true, fn=paste},
	{'.m-px', 'margin__1px;', base=true, fn=paste},
	{'.m-0.5', 'margin__0.125rem;	2px', base=true, fn=paste},
	{'.m-1.5', 'margin__0.375rem;	6px', base=true, fn=paste},
	{'.m-2.5', 'margin__0.625rem;	10px', base=true, fn=paste},
	{'.m-3.5', 'margin__0.875rem;	14px', base=true, fn=paste},
	{'.-m-0', 'margin__0px;', base=true, fn=paste},
	{'.-m-1', 'margin___0.25rem;	_4px', base=true, fn=paste},
	{'.-m-2', 'margin___0.5rem;	_8px', base=true, fn=paste},
	{'.-m-3', 'margin___0.75rem;	_12px', base=true, fn=paste},
	{'.-m-4', 'margin___1rem;	_16px', base=true, fn=paste},
	{'.-m-5', 'margin___1.25rem;	_20px', base=true, fn=paste},
	{'.-m-6', 'margin___1.5rem;	_24px', base=true, fn=paste},
	{'.-m-7', 'margin___1.75rem;	_28px', base=true, fn=paste},
	{'.-m-8', 'margin___2rem;	_32px', base=true, fn=paste},
	{'.-m-9', 'margin___2.25rem;	_36px', base=true, fn=paste},
	{'.-m-10', 'margin___2.5rem;	_40px', base=true, fn=paste},
	{'.-m-11', 'margin___2.75rem;	_44px', base=true, fn=paste},
	{'.-m-12', 'margin___3rem;	_48px', base=true, fn=paste},
	{'.-m-14', 'margin___3.5rem;	_56px', base=true, fn=paste},
	{'.-m-16', 'margin___4rem;	_64px', base=true, fn=paste},
	{'.-m-20', 'margin___5rem;	_80px', base=true, fn=paste},
	{'.-m-24', 'margin___6rem;	_96px', base=true, fn=paste},
	{'.-m-28', 'margin___7rem;	_112px', base=true, fn=paste},
	{'.-m-32', 'margin___8rem;	_128px', base=true, fn=paste},
	{'.-m-36', 'margin___9rem;	_144px', base=true, fn=paste},
	{'.-m-40', 'margin___10rem;	_160px', base=true, fn=paste},
	{'.-m-44', 'margin___11rem;	_176px', base=true, fn=paste},
	{'.-m-48', 'margin___12rem;	_192px', base=true, fn=paste},
	{'.-m-52', 'margin___13rem;	_208px', base=true, fn=paste},
	{'.-m-56', 'margin___14rem;	_224px', base=true, fn=paste},
	{'.-m-60', 'margin___15rem;	_240px', base=true, fn=paste},
	{'.-m-64', 'margin___16rem;	_256px', base=true, fn=paste},
	{'.-m-72', 'margin___18rem;	_288px', base=true, fn=paste},
	{'.-m-80', 'margin___20rem;	_320px', base=true, fn=paste},
	{'.-m-96', 'margin___24rem;	_384px', base=true, fn=paste},
	{'.-m-px', 'margin___1px;', base=true, fn=paste},
	{'.-m-0.5', 'margin___0.125rem;	_2px', base=true, fn=paste},
	{'.-m-1.5', 'margin___0.375rem;	_6px', base=true, fn=paste},
	{'.-m-2.5', 'margin___0.625rem;	_10px', base=true, fn=paste},
	{'.-m-3.5', 'margin___0.875rem;	_14px', base=true, fn=paste},
	{'.mx-0', 'margin_left__0px; margin_right__0px;', base=true, fn=paste},
	{'.mx-1', 'margin_left__0.25rem; margin_right__0.25rem;	4px', base=true, fn=paste},
	{'.mx-2', 'margin_left__0.5rem; margin_right__0.5rem;	8px', base=true, fn=paste},
	{'.mx-3', 'margin_left__0.75rem; margin_right__0.75rem;	12px', base=true, fn=paste},
	{'.mx-4', 'margin_left__1rem; margin_right__1rem;	16px', base=true, fn=paste},
	{'.mx-5', 'margin_left__1.25rem; margin_right__1.25rem;	20px', base=true, fn=paste},
	{'.mx-6', 'margin_left__1.5rem; margin_right__1.5rem;	24px', base=true, fn=paste},
	{'.mx-7', 'margin_left__1.75rem; margin_right__1.75rem;	28px', base=true, fn=paste},
	{'.mx-8', 'margin_left__2rem; margin_right__2rem;	32px', base=true, fn=paste},
	{'.mx-9', 'margin_left__2.25rem; margin_right__2.25rem;	36px', base=true, fn=paste},
	{'.mx-10', 'margin_left__2.5rem; margin_right__2.5rem;	40px', base=true, fn=paste},
	{'.mx-11', 'margin_left__2.75rem; margin_right__2.75rem;	44px', base=true, fn=paste},
	{'.mx-12', 'margin_left__3rem; margin_right__3rem;	48px', base=true, fn=paste},
	{'.mx-14', 'margin_left__3.5rem; margin_right__3.5rem;	56px', base=true, fn=paste},
	{'.mx-16', 'margin_left__4rem; margin_right__4rem;	64px', base=true, fn=paste},
	{'.mx-20', 'margin_left__5rem; margin_right__5rem;	80px', base=true, fn=paste},
	{'.mx-24', 'margin_left__6rem; margin_right__6rem;	96px', base=true, fn=paste},
	{'.mx-28', 'margin_left__7rem; margin_right__7rem;	112px', base=true, fn=paste},
	{'.mx-32', 'margin_left__8rem; margin_right__8rem;	128px', base=true, fn=paste},
	{'.mx-36', 'margin_left__9rem; margin_right__9rem;	144px', base=true, fn=paste},
	{'.mx-40', 'margin_left__10rem; margin_right__10rem;	160px', base=true, fn=paste},
	{'.mx-44', 'margin_left__11rem; margin_right__11rem;	176px', base=true, fn=paste},
	{'.mx-48', 'margin_left__12rem; margin_right__12rem;	192px', base=true, fn=paste},
	{'.mx-52', 'margin_left__13rem; margin_right__13rem;	208px', base=true, fn=paste},
	{'.mx-56', 'margin_left__14rem; margin_right__14rem;	224px', base=true, fn=paste},
	{'.mx-60', 'margin_left__15rem; margin_right__15rem;	240px', base=true, fn=paste},
	{'.mx-64', 'margin_left__16rem; margin_right__16rem;	256px', base=true, fn=paste},
	{'.mx-72', 'margin_left__18rem; margin_right__18rem;	288px', base=true, fn=paste},
	{'.mx-80', 'margin_left__20rem; margin_right__20rem;	320px', base=true, fn=paste},
	{'.mx-96', 'margin_left__24rem; margin_right__24rem;	384px', base=true, fn=paste},
	{'.mx-auto', 'margin_left__auto; margin_right__auto;', base=true, fn=paste},
	{'.mx-px', 'margin_left__1px; margin_right__1px;', base=true, fn=paste},
	{'.mx-0.5', 'margin_left__0.125rem; margin_right__0.125rem;	2px', base=true, fn=paste},
	{'.mx-1.5', 'margin_left__0.375rem; margin_right__0.375rem;	6px', base=true, fn=paste},
	{'.mx-2.5', 'margin_left__0.625rem; margin_right__0.625rem;	10px', base=true, fn=paste},
	{'.mx-3.5', 'margin_left__0.875rem; margin_right__0.875rem;	14px', base=true, fn=paste},
	{'.-mx-0', 'margin_left__0px; margin_right__0px;', base=true, fn=paste},
	{'.-mx-1', 'margin_left___0.25rem; margin_right___0.25rem;	_4px', base=true, fn=paste},
	{'.-mx-2', 'margin_left___0.5rem; margin_right___0.5rem;	_8px', base=true, fn=paste},
	{'.-mx-3', 'margin_left___0.75rem; margin_right___0.75rem;	_12px', base=true, fn=paste},
	{'.-mx-4', 'margin_left___1rem; margin_right___1rem;	_16px', base=true, fn=paste},
	{'.-mx-5', 'margin_left___1.25rem; margin_right___1.25rem;	_20px', base=true, fn=paste},
	{'.-mx-6', 'margin_left___1.5rem; margin_right___1.5rem;	_24px', base=true, fn=paste},
	{'.-mx-7', 'margin_left___1.75rem; margin_right___1.75rem;	_28px', base=true, fn=paste},
	{'.-mx-8', 'margin_left___2rem; margin_right___2rem;	_32px', base=true, fn=paste},
	{'.-mx-9', 'margin_left___2.25rem; margin_right___2.25rem;	_36px', base=true, fn=paste},
	{'.-mx-10', 'margin_left___2.5rem; margin_right___2.5rem;	_40px', base=true, fn=paste},
	{'.-mx-11', 'margin_left___2.75rem; margin_right___2.75rem;	_44px', base=true, fn=paste},
	{'.-mx-12', 'margin_left___3rem; margin_right___3rem;	_48px', base=true, fn=paste},
	{'.-mx-14', 'margin_left___3.5rem; margin_right___3.5rem;	_56px', base=true, fn=paste},
	{'.-mx-16', 'margin_left___4rem; margin_right___4rem;	_64px', base=true, fn=paste},
	{'.-mx-20', 'margin_left___5rem; margin_right___5rem;	_80px', base=true, fn=paste},
	{'.-mx-24', 'margin_left___6rem; margin_right___6rem;	_96px', base=true, fn=paste},
	{'.-mx-28', 'margin_left___7rem; margin_right___7rem;	_112px', base=true, fn=paste},
	{'.-mx-32', 'margin_left___8rem; margin_right___8rem;	_128px', base=true, fn=paste},
	{'.-mx-36', 'margin_left___9rem; margin_right___9rem;	_144px', base=true, fn=paste},
	{'.-mx-40', 'margin_left___10rem; margin_right___10rem;	_160px', base=true, fn=paste},
	{'.-mx-44', 'margin_left___11rem; margin_right___11rem;	_176px', base=true, fn=paste},
	{'.-mx-48', 'margin_left___12rem; margin_right___12rem;	_192px', base=true, fn=paste},
	{'.-mx-52', 'margin_left___13rem; margin_right___13rem;	_208px', base=true, fn=paste},
	{'.-mx-56', 'margin_left___14rem; margin_right___14rem;	_224px', base=true, fn=paste},
	{'.-mx-60', 'margin_left___15rem; margin_right___15rem;	_240px', base=true, fn=paste},
	{'.-mx-64', 'margin_left___16rem; margin_right___16rem;	_256px', base=true, fn=paste},
	{'.-mx-72', 'margin_left___18rem; margin_right___18rem;	_288px', base=true, fn=paste},
	{'.-mx-80', 'margin_left___20rem; margin_right___20rem;	_320px', base=true, fn=paste},
	{'.-mx-96', 'margin_left___24rem; margin_right___24rem;	_384px', base=true, fn=paste},
	{'.-mx-px', 'margin_left___1px; margin_right___1px;', base=true, fn=paste},
	{'.-mx-0.5', 'margin_left___0.125rem; margin_right___0.125rem;	_2px', base=true, fn=paste},
	{'.-mx-1.5', 'margin_left___0.375rem; margin_right___0.375rem;	_6px', base=true, fn=paste},
	{'.-mx-2.5', 'margin_left___0.625rem; margin_right___0.625rem;	_10px', base=true, fn=paste},
	{'.-mx-3.5', 'margin_left___0.875rem; margin_right___0.875rem;	_14px', base=true, fn=paste},
	{'.my-0', 'margin_top__0px; margin_bottom__0px;', base=true, fn=paste},
	{'.my-1', 'margin_top__0.25rem; margin_bottom__0.25rem;	4px', base=true, fn=paste},
	{'.my-2', 'margin_top__0.5rem; margin_bottom__0.5rem;	8px', base=true, fn=paste},
	{'.my-3', 'margin_top__0.75rem; margin_bottom__0.75rem;	12px', base=true, fn=paste},
	{'.my-4', 'margin_top__1rem; margin_bottom__1rem;	16px', base=true, fn=paste},
	{'.my-5', 'margin_top__1.25rem; margin_bottom__1.25rem;	20px', base=true, fn=paste},
	{'.my-6', 'margin_top__1.5rem; margin_bottom__1.5rem;	24px', base=true, fn=paste},
	{'.my-7', 'margin_top__1.75rem; margin_bottom__1.75rem;	28px', base=true, fn=paste},
	{'.my-8', 'margin_top__2rem; margin_bottom__2rem;	32px', base=true, fn=paste},
	{'.my-9', 'margin_top__2.25rem; margin_bottom__2.25rem;	36px', base=true, fn=paste},
	{'.my-10', 'margin_top__2.5rem; margin_bottom__2.5rem;	40px', base=true, fn=paste},
	{'.my-11', 'margin_top__2.75rem; margin_bottom__2.75rem;	44px', base=true, fn=paste},
	{'.my-12', 'margin_top__3rem; margin_bottom__3rem;	48px', base=true, fn=paste},
	{'.my-14', 'margin_top__3.5rem; margin_bottom__3.5rem;	56px', base=true, fn=paste},
	{'.my-16', 'margin_top__4rem; margin_bottom__4rem;	64px', base=true, fn=paste},
	{'.my-20', 'margin_top__5rem; margin_bottom__5rem;	80px', base=true, fn=paste},
	{'.my-24', 'margin_top__6rem; margin_bottom__6rem;	96px', base=true, fn=paste},
	{'.my-28', 'margin_top__7rem; margin_bottom__7rem;	112px', base=true, fn=paste},
	{'.my-32', 'margin_top__8rem; margin_bottom__8rem;	128px', base=true, fn=paste},
	{'.my-36', 'margin_top__9rem; margin_bottom__9rem;	144px', base=true, fn=paste},
	{'.my-40', 'margin_top__10rem; margin_bottom__10rem;	160px', base=true, fn=paste},
	{'.my-44', 'margin_top__11rem; margin_bottom__11rem;	176px', base=true, fn=paste},
	{'.my-48', 'margin_top__12rem; margin_bottom__12rem;	192px', base=true, fn=paste},
	{'.my-52', 'margin_top__13rem; margin_bottom__13rem;	208px', base=true, fn=paste},
	{'.my-56', 'margin_top__14rem; margin_bottom__14rem;	224px', base=true, fn=paste},
	{'.my-60', 'margin_top__15rem; margin_bottom__15rem;	240px', base=true, fn=paste},
	{'.my-64', 'margin_top__16rem; margin_bottom__16rem;	256px', base=true, fn=paste},
	{'.my-72', 'margin_top__18rem; margin_bottom__18rem;	288px', base=true, fn=paste},
	{'.my-80', 'margin_top__20rem; margin_bottom__20rem;	320px', base=true, fn=paste},
	{'.my-96', 'margin_top__24rem; margin_bottom__24rem;	384px', base=true, fn=paste},
	{'.my-auto', 'margin_top__auto; margin_bottom__auto;', base=true, fn=paste},
	{'.my-px', 'margin_top__1px; margin_bottom__1px;', base=true, fn=paste},
	{'.my-0.5', 'margin_top__0.125rem; margin_bottom__0.125rem;	2px', base=true, fn=paste},
	{'.my-1.5', 'margin_top__0.375rem; margin_bottom__0.375rem;	6px', base=true, fn=paste},
	{'.my-2.5', 'margin_top__0.625rem; margin_bottom__0.625rem;	10px', base=true, fn=paste},
	{'.my-3.5', 'margin_top__0.875rem; margin_bottom__0.875rem;	14px', base=true, fn=paste},
	{'.-my-0', 'margin_top__0px; margin_bottom__0px;', base=true, fn=paste},
	{'.-my-1', 'margin_top___0.25rem; margin_bottom___0.25rem;	_4px', base=true, fn=paste},
	{'.-my-2', 'margin_top___0.5rem; margin_bottom___0.5rem;	_8px', base=true, fn=paste},
	{'.-my-3', 'margin_top___0.75rem; margin_bottom___0.75rem;	_12px', base=true, fn=paste},
	{'.-my-4', 'margin_top___1rem; margin_bottom___1rem;	_16px', base=true, fn=paste},
	{'.-my-5', 'margin_top___1.25rem; margin_bottom___1.25rem;	_20px', base=true, fn=paste},
	{'.-my-6', 'margin_top___1.5rem; margin_bottom___1.5rem;	_24px', base=true, fn=paste},
	{'.-my-7', 'margin_top___1.75rem; margin_bottom___1.75rem;	_28px', base=true, fn=paste},
	{'.-my-8', 'margin_top___2rem; margin_bottom___2rem;	_32px', base=true, fn=paste},
	{'.-my-9', 'margin_top___2.25rem; margin_bottom___2.25rem;	_36px', base=true, fn=paste},
	{'.-my-10', 'margin_top___2.5rem; margin_bottom___2.5rem;	_40px', base=true, fn=paste},
	{'.-my-11', 'margin_top___2.75rem; margin_bottom___2.75rem;	_44px', base=true, fn=paste},
	{'.-my-12', 'margin_top___3rem; margin_bottom___3rem;	_48px', base=true, fn=paste},
	{'.-my-14', 'margin_top___3.5rem; margin_bottom___3.5rem;	_56px', base=true, fn=paste},
	{'.-my-16', 'margin_top___4rem; margin_bottom___4rem;	_64px', base=true, fn=paste},
	{'.-my-20', 'margin_top___5rem; margin_bottom___5rem;	_80px', base=true, fn=paste},
	{'.-my-24', 'margin_top___6rem; margin_bottom___6rem;	_96px', base=true, fn=paste},
	{'.-my-28', 'margin_top___7rem; margin_bottom___7rem;	_112px', base=true, fn=paste},
	{'.-my-32', 'margin_top___8rem; margin_bottom___8rem;	_128px', base=true, fn=paste},
	{'.-my-36', 'margin_top___9rem; margin_bottom___9rem;	_144px', base=true, fn=paste},
	{'.-my-40', 'margin_top___10rem; margin_bottom___10rem;	_160px', base=true, fn=paste},
	{'.-my-44', 'margin_top___11rem; margin_bottom___11rem;	_176px', base=true, fn=paste},
	{'.-my-48', 'margin_top___12rem; margin_bottom___12rem;	_192px', base=true, fn=paste},
	{'.-my-52', 'margin_top___13rem; margin_bottom___13rem;	_208px', base=true, fn=paste},
	{'.-my-56', 'margin_top___14rem; margin_bottom___14rem;	_224px', base=true, fn=paste},
	{'.-my-60', 'margin_top___15rem; margin_bottom___15rem;	_240px', base=true, fn=paste},
	{'.-my-64', 'margin_top___16rem; margin_bottom___16rem;	_256px', base=true, fn=paste},
	{'.-my-72', 'margin_top___18rem; margin_bottom___18rem;	_288px', base=true, fn=paste},
	{'.-my-80', 'margin_top___20rem; margin_bottom___20rem;	_320px', base=true, fn=paste},
	{'.-my-96', 'margin_top___24rem; margin_bottom___24rem;	_384px', base=true, fn=paste},
	{'.-my-px', 'margin_top___1px; margin_bottom___1px;', base=true, fn=paste},
	{'.-my-0.5', 'margin_top___0.125rem; margin_bottom___0.125rem;	_2px', base=true, fn=paste},
	{'.-my-1.5', 'margin_top___0.375rem; margin_bottom___0.375rem;	_6px', base=true, fn=paste},
	{'.-my-2.5', 'margin_top___0.625rem; margin_bottom___0.625rem;	_10px', base=true, fn=paste},
	{'.-my-3.5', 'margin_top___0.875rem; margin_bottom___0.875rem;	_14px', base=true, fn=paste},
	{'.mt-0', 'margin_top__0px;', base=true, fn=paste},
	{'.mt-1', 'margin_top__0.25rem;	4px', base=true, fn=paste},
	{'.mt-2', 'margin_top__0.5rem;	8px', base=true, fn=paste},
	{'.mt-3', 'margin_top__0.75rem;	12px', base=true, fn=paste},
	{'.mt-4', 'margin_top__1rem;	16px', base=true, fn=paste},
	{'.mt-5', 'margin_top__1.25rem;	20px', base=true, fn=paste},
	{'.mt-6', 'margin_top__1.5rem;	24px', base=true, fn=paste},
	{'.mt-7', 'margin_top__1.75rem;	28px', base=true, fn=paste},
	{'.mt-8', 'margin_top__2rem;	32px', base=true, fn=paste},
	{'.mt-9', 'margin_top__2.25rem;	36px', base=true, fn=paste},
	{'.mt-10', 'margin_top__2.5rem;	40px', base=true, fn=paste},
	{'.mt-11', 'margin_top__2.75rem;	44px', base=true, fn=paste},
	{'.mt-12', 'margin_top__3rem;	48px', base=true, fn=paste},
	{'.mt-14', 'margin_top__3.5rem;	56px', base=true, fn=paste},
	{'.mt-16', 'margin_top__4rem;	64px', base=true, fn=paste},
	{'.mt-20', 'margin_top__5rem;	80px', base=true, fn=paste},
	{'.mt-24', 'margin_top__6rem;	96px', base=true, fn=paste},
	{'.mt-28', 'margin_top__7rem;	112px', base=true, fn=paste},
	{'.mt-32', 'margin_top__8rem;	128px', base=true, fn=paste},
	{'.mt-36', 'margin_top__9rem;	144px', base=true, fn=paste},
	{'.mt-40', 'margin_top__10rem;	160px', base=true, fn=paste},
	{'.mt-44', 'margin_top__11rem;	176px', base=true, fn=paste},
	{'.mt-48', 'margin_top__12rem;	192px', base=true, fn=paste},
	{'.mt-52', 'margin_top__13rem;	208px', base=true, fn=paste},
	{'.mt-56', 'margin_top__14rem;	224px', base=true, fn=paste},
	{'.mt-60', 'margin_top__15rem;	240px', base=true, fn=paste},
	{'.mt-64', 'margin_top__16rem;	256px', base=true, fn=paste},
	{'.mt-72', 'margin_top__18rem;	288px', base=true, fn=paste},
	{'.mt-80', 'margin_top__20rem;	320px', base=true, fn=paste},
	{'.mt-96', 'margin_top__24rem;	384px', base=true, fn=paste},
	{'.mt-auto', 'margin_top__auto;', base=true, fn=paste},
	{'.mt-px', 'margin_top__1px;', base=true, fn=paste},
	{'.mt-0.5', 'margin_top__0.125rem;	2px', base=true, fn=paste},
	{'.mt-1.5', 'margin_top__0.375rem;	6px', base=true, fn=paste},
	{'.mt-2.5', 'margin_top__0.625rem;	10px', base=true, fn=paste},
	{'.mt-3.5', 'margin_top__0.875rem;	14px', base=true, fn=paste},
	{'.-mt-0', 'margin_top__0px;', base=true, fn=paste},
	{'.-mt-1', 'margin_top___0.25rem;	_4px', base=true, fn=paste},
	{'.-mt-2', 'margin_top___0.5rem;	_8px', base=true, fn=paste},
	{'.-mt-3', 'margin_top___0.75rem;	_12px', base=true, fn=paste},
	{'.-mt-4', 'margin_top___1rem;	_16px', base=true, fn=paste},
	{'.-mt-5', 'margin_top___1.25rem;	_20px', base=true, fn=paste},
	{'.-mt-6', 'margin_top___1.5rem;	_24px', base=true, fn=paste},
	{'.-mt-7', 'margin_top___1.75rem;	_28px', base=true, fn=paste},
	{'.-mt-8', 'margin_top___2rem;	_32px', base=true, fn=paste},
	{'.-mt-9', 'margin_top___2.25rem;	_36px', base=true, fn=paste},
	{'.-mt-10', 'margin_top___2.5rem;	_40px', base=true, fn=paste},
	{'.-mt-11', 'margin_top___2.75rem;	_44px', base=true, fn=paste},
	{'.-mt-12', 'margin_top___3rem;	_48px', base=true, fn=paste},
	{'.-mt-14', 'margin_top___3.5rem;	_56px', base=true, fn=paste},
	{'.-mt-16', 'margin_top___4rem;	_64px', base=true, fn=paste},
	{'.-mt-20', 'margin_top___5rem;	_80px', base=true, fn=paste},
	{'.-mt-24', 'margin_top___6rem;	_96px', base=true, fn=paste},
	{'.-mt-28', 'margin_top___7rem;	_112px', base=true, fn=paste},
	{'.-mt-32', 'margin_top___8rem;	_128px', base=true, fn=paste},
	{'.-mt-36', 'margin_top___9rem;	_144px', base=true, fn=paste},
	{'.-mt-40', 'margin_top___10rem;	_160px', base=true, fn=paste},
	{'.-mt-44', 'margin_top___11rem;	_176px', base=true, fn=paste},
	{'.-mt-48', 'margin_top___12rem;	_192px', base=true, fn=paste},
	{'.-mt-52', 'margin_top___13rem;	_208px', base=true, fn=paste},
	{'.-mt-56', 'margin_top___14rem;	_224px', base=true, fn=paste},
	{'.-mt-60', 'margin_top___15rem;	_240px', base=true, fn=paste},
	{'.-mt-64', 'margin_top___16rem;	_256px', base=true, fn=paste},
	{'.-mt-72', 'margin_top___18rem;	_288px', base=true, fn=paste},
	{'.-mt-80', 'margin_top___20rem;	_320px', base=true, fn=paste},
	{'.-mt-96', 'margin_top___24rem;	_384px', base=true, fn=paste},
	{'.-mt-px', 'margin_top___1px;', base=true, fn=paste},
	{'.-mt-0.5', 'margin_top___0.125rem;	_2px', base=true, fn=paste},
	{'.-mt-1.5', 'margin_top___0.375rem;	_6px', base=true, fn=paste},
	{'.-mt-2.5', 'margin_top___0.625rem;	_10px', base=true, fn=paste},
	{'.-mt-3.5', 'margin_top___0.875rem;	_14px', base=true, fn=paste},
	{'.mr-0', 'margin_right__0px;', base=true, fn=paste},
	{'.mr-1', 'margin_right__0.25rem;	4px', base=true, fn=paste},
	{'.mr-2', 'margin_right__0.5rem;	8px', base=true, fn=paste},
	{'.mr-3', 'margin_right__0.75rem;	12px', base=true, fn=paste},
	{'.mr-4', 'margin_right__1rem;	16px', base=true, fn=paste},
	{'.mr-5', 'margin_right__1.25rem;	20px', base=true, fn=paste},
	{'.mr-6', 'margin_right__1.5rem;	24px', base=true, fn=paste},
	{'.mr-7', 'margin_right__1.75rem;	28px', base=true, fn=paste},
	{'.mr-8', 'margin_right__2rem;	32px', base=true, fn=paste},
	{'.mr-9', 'margin_right__2.25rem;	36px', base=true, fn=paste},
	{'.mr-10', 'margin_right__2.5rem;	40px', base=true, fn=paste},
	{'.mr-11', 'margin_right__2.75rem;	44px', base=true, fn=paste},
	{'.mr-12', 'margin_right__3rem;	48px', base=true, fn=paste},
	{'.mr-14', 'margin_right__3.5rem;	56px', base=true, fn=paste},
	{'.mr-16', 'margin_right__4rem;	64px', base=true, fn=paste},
	{'.mr-20', 'margin_right__5rem;	80px', base=true, fn=paste},
	{'.mr-24', 'margin_right__6rem;	96px', base=true, fn=paste},
	{'.mr-28', 'margin_right__7rem;	112px', base=true, fn=paste},
	{'.mr-32', 'margin_right__8rem;	128px', base=true, fn=paste},
	{'.mr-36', 'margin_right__9rem;	144px', base=true, fn=paste},
	{'.mr-40', 'margin_right__10rem;	160px', base=true, fn=paste},
	{'.mr-44', 'margin_right__11rem;	176px', base=true, fn=paste},
	{'.mr-48', 'margin_right__12rem;	192px', base=true, fn=paste},
	{'.mr-52', 'margin_right__13rem;	208px', base=true, fn=paste},
	{'.mr-56', 'margin_right__14rem;	224px', base=true, fn=paste},
	{'.mr-60', 'margin_right__15rem;	240px', base=true, fn=paste},
	{'.mr-64', 'margin_right__16rem;	256px', base=true, fn=paste},
	{'.mr-72', 'margin_right__18rem;	288px', base=true, fn=paste},
	{'.mr-80', 'margin_right__20rem;	320px', base=true, fn=paste},
	{'.mr-96', 'margin_right__24rem;	384px', base=true, fn=paste},
	{'.mr-auto', 'margin_right__auto;', base=true, fn=paste},
	{'.mr-px', 'margin_right__1px;', base=true, fn=paste},
	{'.mr-0.5', 'margin_right__0.125rem;	2px', base=true, fn=paste},
	{'.mr-1.5', 'margin_right__0.375rem;	6px', base=true, fn=paste},
	{'.mr-2.5', 'margin_right__0.625rem;	10px', base=true, fn=paste},
	{'.mr-3.5', 'margin_right__0.875rem;	14px', base=true, fn=paste},
	{'.-mr-0', 'margin_right__0px;', base=true, fn=paste},
	{'.-mr-1', 'margin_right___0.25rem;	_4px', base=true, fn=paste},
	{'.-mr-2', 'margin_right___0.5rem;	_8px', base=true, fn=paste},
	{'.-mr-3', 'margin_right___0.75rem;	_12px', base=true, fn=paste},
	{'.-mr-4', 'margin_right___1rem;	_16px', base=true, fn=paste},
	{'.-mr-5', 'margin_right___1.25rem;	_20px', base=true, fn=paste},
	{'.-mr-6', 'margin_right___1.5rem;	_24px', base=true, fn=paste},
	{'.-mr-7', 'margin_right___1.75rem;	_28px', base=true, fn=paste},
	{'.-mr-8', 'margin_right___2rem;	_32px', base=true, fn=paste},
	{'.-mr-9', 'margin_right___2.25rem;	_36px', base=true, fn=paste},
	{'.-mr-10', 'margin_right___2.5rem;	_40px', base=true, fn=paste},
	{'.-mr-11', 'margin_right___2.75rem;	_44px', base=true, fn=paste},
	{'.-mr-12', 'margin_right___3rem;	_48px', base=true, fn=paste},
	{'.-mr-14', 'margin_right___3.5rem;	_56px', base=true, fn=paste},
	{'.-mr-16', 'margin_right___4rem;	_64px', base=true, fn=paste},
	{'.-mr-20', 'margin_right___5rem;	_80px', base=true, fn=paste},
	{'.-mr-24', 'margin_right___6rem;	_96px', base=true, fn=paste},
	{'.-mr-28', 'margin_right___7rem;	_112px', base=true, fn=paste},
	{'.-mr-32', 'margin_right___8rem;	_128px', base=true, fn=paste},
	{'.-mr-36', 'margin_right___9rem;	_144px', base=true, fn=paste},
	{'.-mr-40', 'margin_right___10rem;	_160px', base=true, fn=paste},
	{'.-mr-44', 'margin_right___11rem;	_176px', base=true, fn=paste},
	{'.-mr-48', 'margin_right___12rem;	_192px', base=true, fn=paste},
	{'.-mr-52', 'margin_right___13rem;	_208px', base=true, fn=paste},
	{'.-mr-56', 'margin_right___14rem;	_224px', base=true, fn=paste},
	{'.-mr-60', 'margin_right___15rem;	_240px', base=true, fn=paste},
	{'.-mr-64', 'margin_right___16rem;	_256px', base=true, fn=paste},
	{'.-mr-72', 'margin_right___18rem;	_288px', base=true, fn=paste},
	{'.-mr-80', 'margin_right___20rem;	_320px', base=true, fn=paste},
	{'.-mr-96', 'margin_right___24rem;	_384px', base=true, fn=paste},
	{'.-mr-px', 'margin_right___1px;', base=true, fn=paste},
	{'.-mr-0.5', 'margin_right___0.125rem;	_2px', base=true, fn=paste},
	{'.-mr-1.5', 'margin_right___0.375rem;	_6px', base=true, fn=paste},
	{'.-mr-2.5', 'margin_right___0.625rem;	_10px', base=true, fn=paste},
	{'.-mr-3.5', 'margin_right___0.875rem;	_14px', base=true, fn=paste},
	{'.mb-0', 'margin_bottom__0px;', base=true, fn=paste},
	{'.mb-1', 'margin_bottom__0.25rem;	4px', base=true, fn=paste},
	{'.mb-2', 'margin_bottom__0.5rem;	8px', base=true, fn=paste},
	{'.mb-3', 'margin_bottom__0.75rem;	12px', base=true, fn=paste},
	{'.mb-4', 'margin_bottom__1rem;	16px', base=true, fn=paste},
	{'.mb-5', 'margin_bottom__1.25rem;	20px', base=true, fn=paste},
	{'.mb-6', 'margin_bottom__1.5rem;	24px', base=true, fn=paste},
	{'.mb-7', 'margin_bottom__1.75rem;	28px', base=true, fn=paste},
	{'.mb-8', 'margin_bottom__2rem;	32px', base=true, fn=paste},
	{'.mb-9', 'margin_bottom__2.25rem;	36px', base=true, fn=paste},
	{'.mb-10', 'margin_bottom__2.5rem;	40px', base=true, fn=paste},
	{'.mb-11', 'margin_bottom__2.75rem;	44px', base=true, fn=paste},
	{'.mb-12', 'margin_bottom__3rem;	48px', base=true, fn=paste},
	{'.mb-14', 'margin_bottom__3.5rem;	56px', base=true, fn=paste},
	{'.mb-16', 'margin_bottom__4rem;	64px', base=true, fn=paste},
	{'.mb-20', 'margin_bottom__5rem;	80px', base=true, fn=paste},
	{'.mb-24', 'margin_bottom__6rem;	96px', base=true, fn=paste},
	{'.mb-28', 'margin_bottom__7rem;	112px', base=true, fn=paste},
	{'.mb-32', 'margin_bottom__8rem;	128px', base=true, fn=paste},
	{'.mb-36', 'margin_bottom__9rem;	144px', base=true, fn=paste},
	{'.mb-40', 'margin_bottom__10rem;	160px', base=true, fn=paste},
	{'.mb-44', 'margin_bottom__11rem;	176px', base=true, fn=paste},
	{'.mb-48', 'margin_bottom__12rem;	192px', base=true, fn=paste},
	{'.mb-52', 'margin_bottom__13rem;	208px', base=true, fn=paste},
	{'.mb-56', 'margin_bottom__14rem;	224px', base=true, fn=paste},
	{'.mb-60', 'margin_bottom__15rem;	240px', base=true, fn=paste},
	{'.mb-64', 'margin_bottom__16rem;	256px', base=true, fn=paste},
	{'.mb-72', 'margin_bottom__18rem;	288px', base=true, fn=paste},
	{'.mb-80', 'margin_bottom__20rem;	320px', base=true, fn=paste},
	{'.mb-96', 'margin_bottom__24rem;	384px', base=true, fn=paste},
	{'.mb-auto', 'margin_bottom__auto;', base=true, fn=paste},
	{'.mb-px', 'margin_bottom__1px;', base=true, fn=paste},
	{'.mb-0.5', 'margin_bottom__0.125rem;	2px', base=true, fn=paste},
	{'.mb-1.5', 'margin_bottom__0.375rem;	6px', base=true, fn=paste},
	{'.mb-2.5', 'margin_bottom__0.625rem;	10px', base=true, fn=paste},
	{'.mb-3.5', 'margin_bottom__0.875rem;	14px', base=true, fn=paste},
	{'.-mb-0', 'margin_bottom__0px;', base=true, fn=paste},
	{'.-mb-1', 'margin_bottom___0.25rem;	_4px', base=true, fn=paste},
	{'.-mb-2', 'margin_bottom___0.5rem;	_8px', base=true, fn=paste},
	{'.-mb-3', 'margin_bottom___0.75rem;	_12px', base=true, fn=paste},
	{'.-mb-4', 'margin_bottom___1rem;	_16px', base=true, fn=paste},
	{'.-mb-5', 'margin_bottom___1.25rem;	_20px', base=true, fn=paste},
	{'.-mb-6', 'margin_bottom___1.5rem;	_24px', base=true, fn=paste},
	{'.-mb-7', 'margin_bottom___1.75rem;	_28px', base=true, fn=paste},
	{'.-mb-8', 'margin_bottom___2rem;	_32px', base=true, fn=paste},
	{'.-mb-9', 'margin_bottom___2.25rem;	_36px', base=true, fn=paste},
	{'.-mb-10', 'margin_bottom___2.5rem;	_40px', base=true, fn=paste},
	{'.-mb-11', 'margin_bottom___2.75rem;	_44px', base=true, fn=paste},
	{'.-mb-12', 'margin_bottom___3rem;	_48px', base=true, fn=paste},
	{'.-mb-14', 'margin_bottom___3.5rem;	_56px', base=true, fn=paste},
	{'.-mb-16', 'margin_bottom___4rem;	_64px', base=true, fn=paste},
	{'.-mb-20', 'margin_bottom___5rem;	_80px', base=true, fn=paste},
	{'.-mb-24', 'margin_bottom___6rem;	_96px', base=true, fn=paste},
	{'.-mb-28', 'margin_bottom___7rem;	_112px', base=true, fn=paste},
	{'.-mb-32', 'margin_bottom___8rem;	_128px', base=true, fn=paste},
	{'.-mb-36', 'margin_bottom___9rem;	_144px', base=true, fn=paste},
	{'.-mb-40', 'margin_bottom___10rem;	_160px', base=true, fn=paste},
	{'.-mb-44', 'margin_bottom___11rem;	_176px', base=true, fn=paste},
	{'.-mb-48', 'margin_bottom___12rem;	_192px', base=true, fn=paste},
	{'.-mb-52', 'margin_bottom___13rem;	_208px', base=true, fn=paste},
	{'.-mb-56', 'margin_bottom___14rem;	_224px', base=true, fn=paste},
	{'.-mb-60', 'margin_bottom___15rem;	_240px', base=true, fn=paste},
	{'.-mb-64', 'margin_bottom___16rem;	_256px', base=true, fn=paste},
	{'.-mb-72', 'margin_bottom___18rem;	_288px', base=true, fn=paste},
	{'.-mb-80', 'margin_bottom___20rem;	_320px', base=true, fn=paste},
	{'.-mb-96', 'margin_bottom___24rem;	_384px', base=true, fn=paste},
	{'.-mb-px', 'margin_bottom___1px;', base=true, fn=paste},
	{'.-mb-0.5', 'margin_bottom___0.125rem;	_2px', base=true, fn=paste},
	{'.-mb-1.5', 'margin_bottom___0.375rem;	_6px', base=true, fn=paste},
	{'.-mb-2.5', 'margin_bottom___0.625rem;	_10px', base=true, fn=paste},
	{'.-mb-3.5', 'margin_bottom___0.875rem;	_14px', base=true, fn=paste},
	{'.ml-0', 'margin_left__0px;', base=true, fn=paste},
	{'.ml-1', 'margin_left__0.25rem;	4px', base=true, fn=paste},
	{'.ml-2', 'margin_left__0.5rem;	8px', base=true, fn=paste},
	{'.ml-3', 'margin_left__0.75rem;	12px', base=true, fn=paste},
	{'.ml-4', 'margin_left__1rem;	16px', base=true, fn=paste},
	{'.ml-5', 'margin_left__1.25rem;	20px', base=true, fn=paste},
	{'.ml-6', 'margin_left__1.5rem;	24px', base=true, fn=paste},
	{'.ml-7', 'margin_left__1.75rem;	28px', base=true, fn=paste},
	{'.ml-8', 'margin_left__2rem;	32px', base=true, fn=paste},
	{'.ml-9', 'margin_left__2.25rem;	36px', base=true, fn=paste},
	{'.ml-10', 'margin_left__2.5rem;	40px', base=true, fn=paste},
	{'.ml-11', 'margin_left__2.75rem;	44px', base=true, fn=paste},
	{'.ml-12', 'margin_left__3rem;	48px', base=true, fn=paste},
	{'.ml-14', 'margin_left__3.5rem;	56px', base=true, fn=paste},
	{'.ml-16', 'margin_left__4rem;	64px', base=true, fn=paste},
	{'.ml-20', 'margin_left__5rem;	80px', base=true, fn=paste},
	{'.ml-24', 'margin_left__6rem;	96px', base=true, fn=paste},
	{'.ml-28', 'margin_left__7rem;	112px', base=true, fn=paste},
	{'.ml-32', 'margin_left__8rem;	128px', base=true, fn=paste},
	{'.ml-36', 'margin_left__9rem;	144px', base=true, fn=paste},
	{'.ml-40', 'margin_left__10rem;	160px', base=true, fn=paste},
	{'.ml-44', 'margin_left__11rem;	176px', base=true, fn=paste},
	{'.ml-48', 'margin_left__12rem;	192px', base=true, fn=paste},
	{'.ml-52', 'margin_left__13rem;	208px', base=true, fn=paste},
	{'.ml-56', 'margin_left__14rem;	224px', base=true, fn=paste},
	{'.ml-60', 'margin_left__15rem;	240px', base=true, fn=paste},
	{'.ml-64', 'margin_left__16rem;	256px', base=true, fn=paste},
	{'.ml-72', 'margin_left__18rem;	288px', base=true, fn=paste},
	{'.ml-80', 'margin_left__20rem;	320px', base=true, fn=paste},
	{'.ml-96', 'margin_left__24rem;	384px', base=true, fn=paste},
	{'.ml-auto', 'margin_left__auto;', base=true, fn=paste},
	{'.ml-px', 'margin_left__1px;', base=true, fn=paste},
	{'.ml-0.5', 'margin_left__0.125rem;	2px', base=true, fn=paste},
	{'.ml-1.5', 'margin_left__0.375rem;	6px', base=true, fn=paste},
	{'.ml-2.5', 'margin_left__0.625rem;	10px', base=true, fn=paste},
	{'.ml-3.5', 'margin_left__0.875rem;	14px', base=true, fn=paste},
	{'.-ml-0', 'margin_left__0px;', base=true, fn=paste},
	{'.-ml-1', 'margin_left___0.25rem;	_4px', base=true, fn=paste},
	{'.-ml-2', 'margin_left___0.5rem;	_8px', base=true, fn=paste},
	{'.-ml-3', 'margin_left___0.75rem;	_12px', base=true, fn=paste},
	{'.-ml-4', 'margin_left___1rem;	_16px', base=true, fn=paste},
	{'.-ml-5', 'margin_left___1.25rem;	_20px', base=true, fn=paste},
	{'.-ml-6', 'margin_left___1.5rem;	_24px', base=true, fn=paste},
	{'.-ml-7', 'margin_left___1.75rem;	_28px', base=true, fn=paste},
	{'.-ml-8', 'margin_left___2rem;	_32px', base=true, fn=paste},
	{'.-ml-9', 'margin_left___2.25rem;	_36px', base=true, fn=paste},
	{'.-ml-10', 'margin_left___2.5rem;	_40px', base=true, fn=paste},
	{'.-ml-11', 'margin_left___2.75rem;	_44px', base=true, fn=paste},
	{'.-ml-12', 'margin_left___3rem;	_48px', base=true, fn=paste},
	{'.-ml-14', 'margin_left___3.5rem;	_56px', base=true, fn=paste},
	{'.-ml-16', 'margin_left___4rem;	_64px', base=true, fn=paste},
	{'.-ml-20', 'margin_left___5rem;	_80px', base=true, fn=paste},
	{'.-ml-24', 'margin_left___6rem;	_96px', base=true, fn=paste},
	{'.-ml-28', 'margin_left___7rem;	_112px', base=true, fn=paste},
	{'.-ml-32', 'margin_left___8rem;	_128px', base=true, fn=paste},
	{'.-ml-36', 'margin_left___9rem;	_144px', base=true, fn=paste},
	{'.-ml-40', 'margin_left___10rem;	_160px', base=true, fn=paste},
	{'.-ml-44', 'margin_left___11rem;	_176px', base=true, fn=paste},
	{'.-ml-48', 'margin_left___12rem;	_192px', base=true, fn=paste},
	{'.-ml-52', 'margin_left___13rem;	_208px', base=true, fn=paste},
	{'.-ml-56', 'margin_left___14rem;	_224px', base=true, fn=paste},
	{'.-ml-60', 'margin_left___15rem;	_240px', base=true, fn=paste},
	{'.-ml-64', 'margin_left___16rem;	_256px', base=true, fn=paste},
	{'.-ml-72', 'margin_left___18rem;	_288px', base=true, fn=paste},
	{'.-ml-80', 'margin_left___20rem;	_320px', base=true, fn=paste},
	{'.-ml-96', 'margin_left___24rem;	_384px', base=true, fn=paste},
	{'.-ml-px', 'margin_left___1px;', base=true, fn=paste},
	{'.-ml-0.5', 'margin_left___0.125rem;	_2px', base=true, fn=paste},
	{'.-ml-1.5', 'margin_left___0.375rem;	_6px', base=true, fn=paste},
	{'.-ml-2.5', 'margin_left___0.625rem;	_10px', base=true, fn=paste},
	{'.-ml-3.5', 'margin_left___0.875rem;	_14px', base=true, fn=paste},
}