return {
	{'.max-w-0', 'max-width: 0rem;	0px', base=true},
	{'.max-w-none', 'max-width: none;', base=true},
	{'.max-w-xs', 'max-width: 20rem;	320px', base=true},
	{'.max-w-sm', 'max-width: 24rem;	384px', base=true},
	{'.max-w-md', 'max-width: 28rem;	448px', base=true},
	{'.max-w-lg', 'max-width: 32rem;	512px', base=true},
	{'.max-w-xl', 'max-width: 36rem;	576px', base=true},
	{'.max-w-2xl', 'max-width: 42rem;	672px', base=true},
	{'.max-w-3xl', 'max-width: 48rem;	768px', base=true},
	{'.max-w-4xl', 'max-width: 56rem;	896px', base=true},
	{'.max-w-5xl', 'max-width: 64rem;	1024px', base=true},
	{'.max-w-6xl', 'max-width: 72rem;	1152px', base=true},
	{'.max-w-7xl', 'max-width: 80rem;	1280px', base=true},
	{'.max-w-full', 'max-width: 100%;', base=true},
	{'.max-w-min', 'max-width: min-content;', base=true},
	{'.max-w-max', 'max-width: max-content;', base=true},
	{'.max-w-prose', 'max-width: 65ch;', base=true},
	{'.max-w-screen-sm', 'max-width: 640px;', base=true},
	{'.max-w-screen-md', 'max-width: 768px;', base=true},
	{'.max-w-screen-lg', 'max-width: 1024px;', base=true},
	{'.max-w-screen-xl', 'max-width: 1280px;', base=true},
	{'.max-w-screen-2xl', 'max-width: 1536px;', base=true},
}