return {
	{'.max-w-0', 'max_width__0rem;	0px', base=true},
	{'.max-w-none', 'max_width__none;', base=true},
	{'.max-w-xs', 'max_width__20rem;	320px', base=true},
	{'.max-w-sm', 'max_width__24rem;	384px', base=true},
	{'.max-w-md', 'max_width__28rem;	448px', base=true},
	{'.max-w-lg', 'max_width__32rem;	512px', base=true},
	{'.max-w-xl', 'max_width__36rem;	576px', base=true},
	{'.max-w-2xl', 'max_width__42rem;	672px', base=true},
	{'.max-w-3xl', 'max_width__48rem;	768px', base=true},
	{'.max-w-4xl', 'max_width__56rem;	896px', base=true},
	{'.max-w-5xl', 'max_width__64rem;	1024px', base=true},
	{'.max-w-6xl', 'max_width__72rem;	1152px', base=true},
	{'.max-w-7xl', 'max_width__80rem;	1280px', base=true},
	{'.max-w-full', 'max_width__100%;', base=true},
	{'.max-w-min', 'max_width__min_content;', base=true},
	{'.max-w-max', 'max_width__max_content;', base=true},
	{'.max-w-prose', 'max_width__65ch;', base=true},
	{'.max-w-screen-sm', 'max_width__640px;', base=true},
	{'.max-w-screen-md', 'max_width__768px;', base=true},
	{'.max-w-screen-lg', 'max_width__1024px;', base=true},
	{'.max-w-screen-xl', 'max_width__1280px;', base=true},
	{'.max-w-screen-2xl', 'max_width__1536px;', base=true},
}