return {
	{'.mix-blend-normal', 'mix-blend-mode: normal;', base=true},
	{'.mix-blend-multiply', 'mix-blend-mode: multiply;', base=true},
	{'.mix-blend-screen', 'mix-blend-mode: screen;', base=true},
	{'.mix-blend-overlay', 'mix-blend-mode: overlay;', base=true},
	{'.mix-blend-darken', 'mix-blend-mode: darken;', base=true},
	{'.mix-blend-lighten', 'mix-blend-mode: lighten;', base=true},
	{'.mix-blend-color-dodge', 'mix-blend-mode: color-dodge;', base=true},
	{'.mix-blend-color-burn', 'mix-blend-mode: color-burn;', base=true},
	{'.mix-blend-hard-light', 'mix-blend-mode: hard-light;', base=true},
	{'.mix-blend-soft-light', 'mix-blend-mode: soft-light;', base=true},
	{'.mix-blend-difference', 'mix-blend-mode: difference;', base=true},
	{'.mix-blend-exclusion', 'mix-blend-mode: exclusion;', base=true},
	{'.mix-blend-hue', 'mix-blend-mode: hue;', base=true},
	{'.mix-blend-saturation', 'mix-blend-mode: saturation;', base=true},
	{'.mix-blend-color', 'mix-blend-mode: color;', base=true},
	{'.mix-blend-luminosity', 'mix-blend-mode: luminosity;', base=true},
}