return {
	{'.opacity-0', 'opacity__0;', base=true},
	{'.opacity-5', 'opacity__0.05;', base=true},
	{'.opacity-10', 'opacity__0.1;', base=true},
	{'.opacity-20', 'opacity__0.2;', base=true},
	{'.opacity-25', 'opacity__0.25;', base=true},
	{'.opacity-30', 'opacity__0.3;', base=true},
	{'.opacity-40', 'opacity__0.4;', base=true},
	{'.opacity-50', 'opacity__0.5;', base=true},
	{'.opacity-60', 'opacity__0.6;', base=true},
	{'.opacity-70', 'opacity__0.7;', base=true},
	{'.opacity-75', 'opacity__0.75;', base=true},
	{'.opacity-80', 'opacity__0.8;', base=true},
	{'.opacity-90', 'opacity__0.9;', base=true},
	{'.opacity-95', 'opacity__0.95;', base=true},
	{'.opacity-100', 'opacity__1;', base=true},
}