return {
	{'.opacity-0', 'opacity: 0;', base=true},
	{'.opacity-5', 'opacity: 0.05;', base=true},
	{'.opacity-10', 'opacity: 0.1;', base=true},
	{'.opacity-20', 'opacity: 0.2;', base=true},
	{'.opacity-25', 'opacity: 0.25;', base=true},
	{'.opacity-30', 'opacity: 0.3;', base=true},
	{'.opacity-40', 'opacity: 0.4;', base=true},
	{'.opacity-50', 'opacity: 0.5;', base=true},
	{'.opacity-60', 'opacity: 0.6;', base=true},
	{'.opacity-70', 'opacity: 0.7;', base=true},
	{'.opacity-75', 'opacity: 0.75;', base=true},
	{'.opacity-80', 'opacity: 0.8;', base=true},
	{'.opacity-90', 'opacity: 0.9;', base=true},
	{'.opacity-95', 'opacity: 0.95;', base=true},
	{'.opacity-100', 'opacity: 1;', base=true},
}