return {
	{'.order-first', 'order: -9999;', base=true},
	{'.order-last', 'order: 9999;', base=true},
	{'.order-none', 'order: 0;', base=true},
	{'.order-1', 'order: 1;', base=true},
	{'.order-2', 'order: 2;', base=true},
	{'.order-3', 'order: 3;', base=true},
	{'.order-4', 'order: 4;', base=true},
	{'.order-5', 'order: 5;', base=true},
	{'.order-6', 'order: 6;', base=true},
	{'.order-7', 'order: 7;', base=true},
	{'.order-8', 'order: 8;', base=true},
	{'.order-9', 'order: 9;', base=true},
	{'.order-10', 'order: 10;', base=true},
	{'.order-11', 'order: 11;', base=true},
	{'.order-12', 'order: 12;', base=true},
}