return {
	{'.order-first', 'order___9999;', base=true},
	{'.order-last', 'order__9999;', base=true},
	{'.order-none', 'order__0;', base=true},
	{'.order-1', 'order__1;', base=true},
	{'.order-2', 'order__2;', base=true},
	{'.order-3', 'order__3;', base=true},
	{'.order-4', 'order__4;', base=true},
	{'.order-5', 'order__5;', base=true},
	{'.order-6', 'order__6;', base=true},
	{'.order-7', 'order__7;', base=true},
	{'.order-8', 'order__8;', base=true},
	{'.order-9', 'order__9;', base=true},
	{'.order-10', 'order__10;', base=true},
	{'.order-11', 'order__11;', base=true},
	{'.order-12', 'order__12;', base=true},
}