return {
	{'.ring-opacity-0', '--tw-ring-opacity: 0;', base=true},
	{'.ring-opacity-5', '--tw-ring-opacity: 0.05;', base=true},
	{'.ring-opacity-10', '--tw-ring-opacity: 0.1;', base=true},
	{'.ring-opacity-20', '--tw-ring-opacity: 0.2;', base=true},
	{'.ring-opacity-25', '--tw-ring-opacity: 0.25;', base=true},
	{'.ring-opacity-30', '--tw-ring-opacity: 0.3;', base=true},
	{'.ring-opacity-40', '--tw-ring-opacity: 0.4;', base=true},
	{'.ring-opacity-50', '--tw-ring-opacity: 0.5;', base=true},
	{'.ring-opacity-60', '--tw-ring-opacity: 0.6;', base=true},
	{'.ring-opacity-70', '--tw-ring-opacity: 0.7;', base=true},
	{'.ring-opacity-75', '--tw-ring-opacity: 0.75;', base=true},
	{'.ring-opacity-80', '--tw-ring-opacity: 0.8;', base=true},
	{'.ring-opacity-90', '--tw-ring-opacity: 0.9;', base=true},
	{'.ring-opacity-95', '--tw-ring-opacity: 0.95;', base=true},
	{'.ring-opacity-100', '--tw-ring-opacity: 1;', base=true},
}