return {
	{'.rotate-0', '__tw_rotate__0deg;', base=true},
	{'.rotate-1', '__tw_rotate__1deg;', base=true},
	{'.rotate-2', '__tw_rotate__2deg;', base=true},
	{'.rotate-3', '__tw_rotate__3deg;', base=true},
	{'.rotate-6', '__tw_rotate__6deg;', base=true},
	{'.rotate-12', '__tw_rotate__12deg;', base=true},
	{'.rotate-45', '__tw_rotate__45deg;', base=true},
	{'.rotate-90', '__tw_rotate__90deg;', base=true},
	{'.rotate-180', '__tw_rotate__180deg;', base=true},
	{'.-rotate-180', '__tw_rotate___180deg;', base=true},
	{'.-rotate-90', '__tw_rotate___90deg;', base=true},
	{'.-rotate-45', '__tw_rotate___45deg;', base=true},
	{'.-rotate-12', '__tw_rotate___12deg;', base=true},
	{'.-rotate-6', '__tw_rotate___6deg;', base=true},
	{'.-rotate-3', '__tw_rotate___3deg;', base=true},
	{'.-rotate-2', '__tw_rotate___2deg;', base=true},
	{'.-rotate-1', '__tw_rotate___1deg;', base=true},
}