return {
	{'.rotate-0', '--tw-rotate: 0deg;', base=true},
	{'.rotate-1', '--tw-rotate: 1deg;', base=true},
	{'.rotate-2', '--tw-rotate: 2deg;', base=true},
	{'.rotate-3', '--tw-rotate: 3deg;', base=true},
	{'.rotate-6', '--tw-rotate: 6deg;', base=true},
	{'.rotate-12', '--tw-rotate: 12deg;', base=true},
	{'.rotate-45', '--tw-rotate: 45deg;', base=true},
	{'.rotate-90', '--tw-rotate: 90deg;', base=true},
	{'.rotate-180', '--tw-rotate: 180deg;', base=true},
	{'.-rotate-180', '--tw-rotate: -180deg;', base=true},
	{'.-rotate-90', '--tw-rotate: -90deg;', base=true},
	{'.-rotate-45', '--tw-rotate: -45deg;', base=true},
	{'.-rotate-12', '--tw-rotate: -12deg;', base=true},
	{'.-rotate-6', '--tw-rotate: -6deg;', base=true},
	{'.-rotate-3', '--tw-rotate: -3deg;', base=true},
	{'.-rotate-2', '--tw-rotate: -2deg;', base=true},
	{'.-rotate-1', '--tw-rotate: -1deg;', base=true},
}