return {
	{'.skew-x-0', '--tw-skew-x: 0deg;', base=true},
	{'.skew-x-1', '--tw-skew-x: 1deg;', base=true},
	{'.skew-x-2', '--tw-skew-x: 2deg;', base=true},
	{'.skew-x-3', '--tw-skew-x: 3deg;', base=true},
	{'.skew-x-6', '--tw-skew-x: 6deg;', base=true},
	{'.skew-x-12', '--tw-skew-x: 12deg;', base=true},
	{'.-skew-x-12', '--tw-skew-x: -12deg;', base=true},
	{'.-skew-x-6', '--tw-skew-x: -6deg;', base=true},
	{'.-skew-x-3', '--tw-skew-x: -3deg;', base=true},
	{'.-skew-x-2', '--tw-skew-x: -2deg;', base=true},
	{'.-skew-x-1', '--tw-skew-x: -1deg;', base=true},
	{'.skew-y-0', '--tw-skew-y: 0deg;', base=true},
	{'.skew-y-1', '--tw-skew-y: 1deg;', base=true},
	{'.skew-y-2', '--tw-skew-y: 2deg;', base=true},
	{'.skew-y-3', '--tw-skew-y: 3deg;', base=true},
	{'.skew-y-6', '--tw-skew-y: 6deg;', base=true},
	{'.skew-y-12', '--tw-skew-y: 12deg;', base=true},
	{'.-skew-y-12', '--tw-skew-y: -12deg;', base=true},
	{'.-skew-y-6', '--tw-skew-y: -6deg;', base=true},
	{'.-skew-y-3', '--tw-skew-y: -3deg;', base=true},
	{'.-skew-y-2', '--tw-skew-y: -2deg;', base=true},
	{'.-skew-y-1', '--tw-skew-y: -1deg;', base=true},
}