return {
	{'.skew-x-0', '__tw_skew_x__0deg;', base=true},
	{'.skew-x-1', '__tw_skew_x__1deg;', base=true},
	{'.skew-x-2', '__tw_skew_x__2deg;', base=true},
	{'.skew-x-3', '__tw_skew_x__3deg;', base=true},
	{'.skew-x-6', '__tw_skew_x__6deg;', base=true},
	{'.skew-x-12', '__tw_skew_x__12deg;', base=true},
	{'.-skew-x-12', '__tw_skew_x___12deg;', base=true},
	{'.-skew-x-6', '__tw_skew_x___6deg;', base=true},
	{'.-skew-x-3', '__tw_skew_x___3deg;', base=true},
	{'.-skew-x-2', '__tw_skew_x___2deg;', base=true},
	{'.-skew-x-1', '__tw_skew_x___1deg;', base=true},
	{'.skew-y-0', '__tw_skew_y__0deg;', base=true},
	{'.skew-y-1', '__tw_skew_y__1deg;', base=true},
	{'.skew-y-2', '__tw_skew_y__2deg;', base=true},
	{'.skew-y-3', '__tw_skew_y__3deg;', base=true},
	{'.skew-y-6', '__tw_skew_y__6deg;', base=true},
	{'.skew-y-12', '__tw_skew_y__12deg;', base=true},
	{'.-skew-y-12', '__tw_skew_y___12deg;', base=true},
	{'.-skew-y-6', '__tw_skew_y___6deg;', base=true},
	{'.-skew-y-3', '__tw_skew_y___3deg;', base=true},
	{'.-skew-y-2', '__tw_skew_y___2deg;', base=true},
	{'.-skew-y-1', '__tw_skew_y___1deg;', base=true},
}