return {
	{'.text-opacity-0', '__tw_text_opacity__0;', base=true},
	{'.text-opacity-5', '__tw_text_opacity__0.05;', base=true},
	{'.text-opacity-10', '__tw_text_opacity__0.1;', base=true},
	{'.text-opacity-20', '__tw_text_opacity__0.2;', base=true},
	{'.text-opacity-25', '__tw_text_opacity__0.25;', base=true},
	{'.text-opacity-30', '__tw_text_opacity__0.3;', base=true},
	{'.text-opacity-40', '__tw_text_opacity__0.4;', base=true},
	{'.text-opacity-50', '__tw_text_opacity__0.5;', base=true},
	{'.text-opacity-60', '__tw_text_opacity__0.6;', base=true},
	{'.text-opacity-70', '__tw_text_opacity__0.7;', base=true},
	{'.text-opacity-75', '__tw_text_opacity__0.75;', base=true},
	{'.text-opacity-80', '__tw_text_opacity__0.8;', base=true},
	{'.text-opacity-90', '__tw_text_opacity__0.9;', base=true},
	{'.text-opacity-95', '__tw_text_opacity__0.95;', base=true},
	{'.text-opacity-100', '__tw_text_opacity__1;', base=true},
}