return {
	{'text color', 'text_color', doc='https://tailwindcss.com/docs/text-color'},
	{'text opacity', 'text_opacity', doc='https://tailwindcss.com/docs/text-color'},
	{'font-family', 'font_family', doc='https://tailwindcss.com/docs/fonts'},
	{'font-size', 'font_size', doc='https://tailwindcss.com/docs/text-sizing'},
	{'font-smoothing', 'font_smoothing', doc='https://tailwindcss.com/docs/text-style'},
	{'font-style', 'font_style', doc='https://tailwindcss.com/docs/text-style'},
	{'font-weight', 'font_weight', doc='https://tailwindcss.com/docs/font-weight'},
	{'font-variant-numeric', 'font_variant_numeric', doc='https://tailwindcss.com/docs/font-variant-numeric'},
	{'letter-spacing', 'letter_spacing', doc='https://tailwindcss.com/docs/letter-spacing'},
	{'line-height', 'line_height', doc='https://tailwindcss.com/docs/line-height'},
	{'list-style-type', 'list_style_type', doc='https://tailwindcss.com/docs/list-style-type'},
	{'list-style-position', 'list_style_position', doc='https://tailwindcss.com/docs/list-style-position'},
	{'::placeholder color', '__placeholder_color', doc='https://tailwindcss.com/docs/placeholder-color'},
	{'::placeholder opacity', '__placeholder_opacity', doc='https://tailwindcss.com/docs/placeholder-opacity'},
	{'text-align', 'text_align', doc='https://tailwindcss.com/docs/text-alignment'},
	{'text-decoration', 'text_decoration', doc='https://tailwindcss.com/docs/text-decoration'},
	{'text-transform', 'text_transform', doc='https://tailwindcss.com/docs/text-transform'},
	{'text-overflow', 'text_overflow', doc='https://tailwindcss.com/docs/text-overflow'},
	{'vertical-align', 'vertical_align', doc='https://tailwindcss.com/docs/vertical-alignment'},
	{'white-space', 'white_space', doc='https://tailwindcss.com/docs/whitespace'},
	{'word-break', 'word_break', doc='https://tailwindcss.com/docs/word-break'},
}