return {
	{'text color', 'text_color', doc='https://tailwindcss.com/docs/text-color', desc='Sets the text color.'},
	{'text opacity', 'text_opacity', doc='https://tailwindcss.com/docs/text-color', desc='Sets text opacity when used with text-[color].'},
	{'font-family', 'font_family', doc='https://tailwindcss.com/docs/fonts', desc='Sets the font family.'},
	{'font-size', 'font_size', doc='https://tailwindcss.com/docs/text-sizing', desc='Sets the font size.'},
	{'font-smoothing', 'font_smoothing', doc='https://tailwindcss.com/docs/text-style', desc='Sets the antialiasing of the font.'},
	{'font-style', 'font_style', doc='https://tailwindcss.com/docs/text-style', desc='Sets the style of the font.'},
	{'font-weight', 'font_weight', doc='https://tailwindcss.com/docs/font-weight', desc='Sets the font weight.'},
	{'font-variant-numeric', 'font_variant_numeric', doc='https://tailwindcss.com/docs/font-variant-numeric', desc='Sets the font number variant.'},
	{'letter-spacing', 'letter_spacing', doc='https://tailwindcss.com/docs/letter-spacing', desc='Sets the spacing between letters.'},
	{'line-height', 'line_height', doc='https://tailwindcss.com/docs/line-height', desc='Sets the line height.'},
	{'list-style-type', 'list_style_type', doc='https://tailwindcss.com/docs/list-style-type', desc='Sets the bullet style of a list.'},
	{'list-style-position', 'list_style_position', doc='https://tailwindcss.com/docs/list-style-position', desc='Sets the position of a list\'s bullets.'},
	{'::placeholder color', '__placeholder_color', doc='https://tailwindcss.com/docs/placeholder-color', desc='Sets the placeholder color using the ::placeholder pseudo element.'},
	{'::placeholder opacity', '__placeholder_opacity', doc='https://tailwindcss.com/docs/placeholder-opacity', desc='Sets the placeholder opacity when used with placeholder-[color].'},
	{'text-align', 'text_align', doc='https://tailwindcss.com/docs/text-alignment', desc='Sets the alignment of text.'},
	{'text-decoration', 'text_decoration', doc='https://tailwindcss.com/docs/text-decoration', desc='Sets the text-decoration of an element.'},
	{'text-transform', 'text_transform', doc='https://tailwindcss.com/docs/text-transform', desc='Sets the capitalization of text.'},
	{'text-overflow', 'text_overflow', doc='https://tailwindcss.com/docs/text-overflow', desc='Sets the overflow of text.'},
	{'vertical-align', 'vertical_align', doc='https://tailwindcss.com/docs/vertical-alignment', desc='Sets the vertical alignment of an inline or table-cell box.'},
	{'white-space', 'white_space', doc='https://tailwindcss.com/docs/whitespace', desc='Sets the whitespace of an element.'},
	{'word-break', 'word_break', doc='https://tailwindcss.com/docs/word-break', desc='Sets the word breaks of an element.'},
}