return {
	{"Cheat Sheet", "cheat-sheet"},
	{"Accent Color", "accent-color"},
	{"Adding Custom Styles", "adding-custom-styles"},
	{"Align Content", "align-content"},
	{"Align Items", "align-items"},
	{"Align Self", "align-self"},
	{"Animation", "animation"},
	{"Appearance", "appearance"},
	{"Aspect Ratio", "aspect-ratio"},
	{"Backdrop Blur", "backdrop-blur"},
	{"Backdrop Brightness", "backdrop-brightness"},
	{"Backdrop Contrast", "backdrop-contrast"},
	{"Backdrop Grayscale", "backdrop-grayscale"},
	{"Backdrop Hue Rotate", "backdrop-hue-rotate"},
	{"Backdrop Invert", "backdrop-invert"},
	{"Backdrop Opacity", "backdrop-opacity"},
	{"Backdrop Saturate", "backdrop-saturate"},
	{"Backdrop Sepia", "backdrop-sepia"},
	{"Background Attachment", "background-attachment"},
	{"Background Blend Mode", "background-blend-mode"},
	{"Background Clip", "background-clip"},
	{"Background Color", "background-color"},
	{"Background Image", "background-image"},
	{"Background Origin", "background-origin"},
	{"Background Position", "background-position"},
	{"Background Repeat", "background-repeat"},
	{"Background Size", "background-size"},
	{"Blur", "blur"},
	{"Border Collapse", "border-collapse"},
	{"Border Color", "border-color"},
	{"Border Radius", "border-radius"},
	{"Border Spacing", "border-spacing"},
	{"Border Style", "border-style"},
	{"Border Width", "border-width"},
	{"Box Decoration Break", "box-decoration-break"},
	{"Box Shadow", "box-shadow"},
	{"Box Shadow Color", "box-shadow-color"},
	{"Box Sizing", "box-sizing"},
	{"Break After", "break-after"},
	{"Break Before", "break-before"},
	{"Break Inside", "break-inside"},
	{"Brightness", "brightness"},
	{"Browser Support", "browser-support"},
	{"Caret Color", "caret-color"},
	{"Clear", "clear"},
	{"Columns", "columns"},
	{"Configuration", "configuration"},
	{"Container", "container"},
	{"Content", "content"},
	{"Content Configuration", "content-configuration"},
	{"Contrast", "contrast"},
	{"Cursor", "cursor"},
	{"Customizing Colors", "customizing-colors"},
	{"Customizing Spacing", "customizing-spacing"},
	{"Dark Mode", "dark-mode"},
	{"Display", "display"},
	{"Divide Color", "divide-color"},
	{"Divide Style", "divide-style"},
	{"Divide Width", "divide-width"},
	{"Drop Shadow", "drop-shadow"},
	{"Editor Setup", "editor-setup"},
	{"Fill", "fill"},
	{"Flex", "flex"},
	{"Flex Basis", "flex-basis"},
	{"Flex Direction", "flex-direction"},
	{"Flex Grow", "flex-grow"},
	{"Flex Shrink", "flex-shrink"},
	{"Flex Wrap", "flex-wrap"},
	{"Float", "float"},
	{"Font Family", "font-family"},
	{"Font Size", "font-size"},
	{"Font Smoothing", "font-smoothing"},
	{"Font Style", "font-style"},
	{"Font Variant Numeric", "font-variant-numeric"},
	{"Font Weight", "font-weight"},
	{"Functions And Directives", "functions-and-directives"},
	{"Gap", "gap"},
	{"Gradient Color Stops", "gradient-color-stops"},
	{"Grayscale", "grayscale"},
	{"Grid Auto Columns", "grid-auto-columns"},
	{"Grid Auto Flow", "grid-auto-flow"},
	{"Grid Auto Rows", "grid-auto-rows"},
	{"Grid Column", "grid-column"},
	{"Grid Row", "grid-row"},
	{"Grid Template Columns", "grid-template-columns"},
	{"Grid Template Rows", "grid-template-rows"},
	{"Height", "height"},
	{"Hover Focus And Other States", "hover-focus-and-other-states"},
	{"Hue Rotate", "hue-rotate"},
	{"Installation", "installation"},
	{"Invert", "invert"},
	{"Isolation", "isolation"},
	{"Justify Content", "justify-content"},
	{"Justify Items", "justify-items"},
	{"Justify Self", "justify-self"},
	{"Letter Spacing", "letter-spacing"},
	{"Line Height", "line-height"},
	{"List Style Position", "list-style-position"},
	{"List Style Type", "list-style-type"},
	{"Margin", "margin"},
	{"Max Height", "max-height"},
	{"Max Width", "max-width"},
	{"Min Height", "min-height"},
	{"Min Width", "min-width"},
	{"Mix Blend Mode", "mix-blend-mode"},
	{"Object Fit", "object-fit"},
	{"Object Position", "object-position"},
	{"Opacity", "opacity"},
	{"Optimizing For Production", "optimizing-for-production"},
	{"Order", "order"},
	{"Outline Color", "outline-color"},
	{"Outline Offset", "outline-offset"},
	{"Outline Style", "outline-style"},
	{"Outline Width", "outline-width"},
	{"Overflow", "overflow"},
	{"Overscroll Behavior", "overscroll-behavior"},
	{"Padding", "padding"},
	{"Place Content", "place-content"},
	{"Place Items", "place-items"},
	{"Place Self", "place-self"},
	{"Plugins", "plugins"},
	{"Pointer Events", "pointer-events"},
	{"Position", "position"},
	{"Preflight", "preflight"},
	{"Presets", "presets"},
	{"Resize", "resize"},
	{"Responsive Design", "responsive-design"},
	{"Reusing Styles", "reusing-styles"},
	{"Ring Color", "ring-color"},
	{"Ring Offset Color", "ring-offset-color"},
	{"Ring Offset Width", "ring-offset-width"},
	{"Ring Width", "ring-width"},
	{"Rotate", "rotate"},
	{"Saturate", "saturate"},
	{"Scale", "scale"},
	{"Screen Readers", "screen-readers"},
	{"Screens", "screens"},
	{"Scroll Behavior", "scroll-behavior"},
	{"Scroll Margin", "scroll-margin"},
	{"Scroll Padding", "scroll-padding"},
	{"Scroll Snap Align", "scroll-snap-align"},
	{"Scroll Snap Stop", "scroll-snap-stop"},
	{"Scroll Snap Type", "scroll-snap-type"},
	{"Sepia", "sepia"},
	{"Skew", "skew"},
	{"Space", "space"},
	{"Stroke", "stroke"},
	{"Stroke Width", "stroke-width"},
	{"Table Layout", "table-layout"},
	{"Text Align", "text-align"},
	{"Text Color", "text-color"},
	{"Text Decoration", "text-decoration"},
	{"Text Decoration Color", "text-decoration-color"},
	{"Text Decoration Style", "text-decoration-style"},
	{"Text Decoration Thickness", "text-decoration-thickness"},
	{"Text Indent", "text-indent"},
	{"Text Overflow", "text-overflow"},
	{"Text Transform", "text-transform"},
	{"Text Underline Offset", "text-underline-offset"},
	{"Theme", "theme"},
	{"Top Right Bottom Left", "top-right-bottom-left"},
	{"Touch Action", "touch-action"},
	{"Transform Origin", "transform-origin"},
	{"Transition Delay", "transition-delay"},
	{"Transition Duration", "transition-duration"},
	{"Transition Property", "transition-property"},
	{"Transition Timing Function", "transition-timing-function"},
	{"Translate", "translate"},
	{"Typography Plugin", "typography-plugin"},
	{"Upgrade Guide", "upgrade-guide"},
	{"User Select", "user-select"},
	{"Using With Preprocessors", "using-with-preprocessors"},
	{"Utility First", "utility-first"},
	{"Vertical Align", "vertical-align"},
	{"Visibility", "visibility"},
	{"Whitespace", "whitespace"},
	{"Width", "width"},
	{"Will Change", "will-change"},
	{"Word Break", "word-break"},
	{"Z Index", "z-index"},
}